def origin_text(a, b):
    return "Add an empty object origin as the rotation axis (if there is an " \
           "origin, " + a + \
        "), and set the origin position " + b + " during operation"
desc = "Set Object Origin to Bounding Box Bottom Center"
desc += "\nALT: Determine Bottom Center based on Evaluated Mesh, taking Modifiers into account"
not_add = "do not add it"
data = {
    "Create new Pose based on {}'s current Rotation":"基于 {} 当前的旋转创建新的姿势",
    "Create linked Batch Poses for {} and all Group Empties under it":"为 {} 及其下所有组空物体创建链接的批处理姿势",
    'Select Box': '框选',
    'Hyper Cursor': '高级光标',
    'Simple Hyper Cursor': '简易高级光标',
    'Assetbrowser Tools': '资产浏览器',
    'Easy Assemly Asset Creation and Import via the Asset Browser': '通过资产浏览器轻松创建和导入资产',
    'Select Lasoo': '套索选择',
    'Entering the sculpt mode will be displayed in the top bar': '进入雕刻模式将会在顶栏显示',
    'theKeyActionIsAClick': '按键操作是单击',
    'writePropertyFileError': '写入属性文件错误',
    'DisplayedAllTheTime': '一直显示',
    'SculptModeOnly': '仅雕刻模式',
    'BbrushModeOnly': '仅Bbrush模式',
    'NotShown': '不显示',
    'Reset Modified Keymaps to Default': '将修改过的快捷键重置为默认设置',
    'Restore Missing Keymaps': '恢复缺失的快捷键',
    'Keep the silhouette displayed all the time, even when not in sculpting mode': '一直保持显示剪影图,即使不在雕刻模式',
    'Display silhouette images only in sculpting mode': '仅在雕刻模式显示剪影图',
    'Only in Bbrush mode, the silhouette is displayed': '仅在Bbrush模式时,显示剪影图',
    'Never display silhouette images at any time': '任何时候都不显示剪影图',
    'Silhouette Display Mode': '剪影图显示模式',
    'Silhouette image scaling': '剪影图缩放',
    'Silhouette image offset X': '剪影图偏移X',
    'Silhouette image offset Y': '剪影图偏移Y',
    'Shortcut key offset X': '快捷键偏移X',
    'Shortcut key offset Y': '快捷键偏移Y',
    'Always use Bbrush sculpting mode': '始终使用Bbrush雕刻模式',
    'If entering sculpting mode, Bbrush mode will automatically activate; if exiting sculpting mode, Bbrush mode will deactivate': '如果进入雕刻模式则自动开启Bbrush模式,退出雕刻模式则退出Bbrush模式',
    'Depth ray check size': '深度射线检查大小',
    'Display shortcut keys': '显示快捷键',
    'Shortcut key offset': '快捷键偏移',
    'Shortcut key display size': '快捷键显示大小',
    'Silhouette:': '剪影图',
    'shortcut:': '快捷键',
    'Setting log file path error': '设置Log文件路径错误',
    "Check if the mouse is placed over the model, mouse cursor's range size": '检查鼠标是否放在模型上,鼠标范围大小',
    'Control handle for moving the sculpting origin': '用于移动雕刻原点的操作控制柄',
    'Polygon mask': '多边形绘制遮罩',
    'Draw polygonal mask': '绘制多边形遮罩',
    'Square mask': '方形绘制遮罩',
    'Draw square mask': '绘制方形遮罩',
    'Circular mask': '圆形绘制遮罩',
    'Draw circular mask': '绘制圆形遮罩',
    'Ellipse mask': '椭圆遮罩',
    'Draw elliptical mask': '绘制椭圆遮罩',
    'View operations': '视图操作',
    'Pan view': '平移视图',
    'Rotate view': '旋转视图',
    'Zoom view': '缩放视图',
    'Tilt view': '倾斜视图',
    'alt+right or alt+middle': 'ALT+右键 or ALT+中键',
    'alt+left Drag in blank area': '在空白处ALT+左键拖拽',
    'shift+middle': 'shift+中键',
    'left Drag in blank area': '在空白处左键拖拽',
    'ctrl+middle or ctrl+right': 'ctrl+中键 或 ctrl+右键',
    'shift+left Drag in blank area': '在空白处shift+左键拖拽',
    'left Paint on the model': '左键在模型上绘制',
    'alt+left Paint on the model': 'alt+左键在模型上绘制',
    'shift+left Paint on the model': 'shift+左键在模型上绘制',
    'alt+left Click on other models': 'alt+左键在模型上单击',
    'ctrl+left Paint on the model': 'ctrl+左键在模型上绘制',
    'ctrl+alt+left Paint on the model': 'ctrl+alt+左键在模型上绘制',
    'ctrl+left Drag in blank area': '在空白处ctrl+左键拖拽',
    'ctrl+left Drag from a blank area to the model': '在空白处ctrl+左键拖拽到模型上',
    'ctrl+alt+left Drag from a blank area to the model': '在空白处ctrl+alt+左键拖拽到模型上',
    'ctrl+left Click on the model': 'ctrl+左键单击模型',
    'ctrl+alt+left Click on the model': 'ctrl+alt+左键在模型上单击',
    'ctrl+alt+left Drag in blank area': '在空白处ctrl+alt+左键拖拽',
    'ctrl+Numpad+ Click': 'ctrl+数字+ 左键单击',
    'ctrl+Numpad- Click': 'ctrl+数字- 左键单击',
    'ctrl+Up arrow or ctrl+Numpad* Click': 'ctrl+方向上 或 数字* 左键单击',
    'ctrl+Down arrow or ctrl+Numpad/ Click': 'ctrl+方向下 或 数字/ 左键单击',
    'ctrl+shift+left Paint on the model': 'ctrl+shift+左键在模型上绘制',
    'ctrl+shift+alt+left Paint on the model': 'ctrl+shift+alt+左键在模型上绘制',
    'ctrl+shift+left Click in blank area': '在空白处ctrl+shift+左键单击',
    'ctrl+shift+left or ctrl+shift+alt+left Drag in blank area': '在空白处ctrl+shift 或 ctrl+shift+alt+左键拖拽',

    'mouse_right': '右键',
    'middle': '中键',
    'left': '左键',
    'click': '单击',
    'Numpad': '小键盘',
    'Reverse sculpt': '反向雕刻',
    'Smooth': '平滑',
    'Switch object': '切换雕刻物体',
    'Draw mask': '绘制遮罩',
    'Erase mask': '擦除遮罩',
    'Invert mask': '反转遮罩',
    'Marquee mask': '框选遮罩',
    'erase mask': '框选擦除遮罩',
    'Fade mask': '淡化遮罩',
    'Clear mask': '清除遮罩',
    'Sharpen mask': '锐化遮罩',
    'Fill mask': '填充遮罩',
    'Grow mask': '生长遮罩',
    'Shrink mask': '收缩遮罩',
    'Increase contrast': '提高遮罩对比度',
    'Decrease contrast': '降低遮罩对比度',
    'Hide': '隐藏',
    'Hide outside': '隐藏绘制框外',
    'Hide inside': '隐藏绘制框内',
    'Unhide': '取消隐藏',
    'Invert visibility': '反转隐藏',
    'Up arrow': '上箭头',
    'Down arrow': '下箭头',
    'Brush mode switch': '笔刷模式切换',
    'Switch brush content, with a list of options for each key, including [sculpt, mask, hide]': '切换笔刷内容,每个键的列表，有[雕刻,遮罩,隐藏]三个功能',
    'Depth map zoom value': '深度图缩放值',
    'Bbrush sculpting': 'Bbrush雕刻',
    'Sculpting in the style of Zbrush': '使用Zbrush的方式雕刻',
    'Only the front faces': '仅前面的面',
    'The key operation is a single click': '按键操作是单击',
    'Error in acquiring shape projection': '获取形状投射错误',
    'Bbrush mask': 'Bbrush遮罩',
    'Mask brush': '遮罩笔刷',
    'Display top text': '显示顶部文本',
    'Depth ray check size(px)': '深度射线检查大小(px)',
    'Mirror vertex groups weights, clean vertex groups': '镜像顶点组，清理顶点组',
    'Mirror weights': '镜像顶点组',
    'Mirror vertex groups weights': '镜像顶点组权重',
    'Clear unused': '删除没有使用',
    'Clear zero': '删除权重为零',
    'Mirror completed!': '镜像完毕!',
    'You cannot select both left and right bones simultaneously!': '不能同时选择左右两边的骨骼!',
    'Multiple vertex groups will be mirrored.': '将会镜像多个顶点组',
    'The object does not have vertex groups.': '对象没有顶点组',
    'Delete vertex groups with a total weight of 0 within the vertex group.': '删除权重为0的顶点组',
    'Delete unused vertex groups.': '删除没有使用的顶点组',
    'Mirror method': '镜像方法',
    'Nearest': '最近点',
    'Polyinterp': '面插值',
    'Nearest vertex': '最近的顶点',
    'Nearest face interpolation': '最近的面插值',
    'Mirror direction': '镜像方向',
    'Select mirror direction': '选择镜像方向',
    'Symmetric': '对称',
    'Multiple vertex groups': '多个顶点组',
    'Mirror or symmetrize multiple vertex groups.': '镜像或者对称多个顶点组',
    'Selected': '选中的',
    'Delete vertex groups with a total weight of 0': '删除总权重为0的顶点组',
    'Mirror or symmetrize selected vertex groups (selected bones, in weight paint mode)': '镜像或者对称选中的顶点组(选中的骨骼，需要在权重绘制模式)',
    'When enabled, make the middle bone symmetrical weight; when disabled, mirror the weight between the left and right bones.': '开启时使中间骨骼对称权重，关闭时使左右两边的骨骼镜像权重',
    '(-x arrow<-) Use the weight on the right side +x -> -x': '(-x箭头<-)使用右边权重+x->-x',
    '(+x arrow->) Use the weight on the left side -x -> +x': '(+x箭头->)使用左边权重-x->+x',
    'When left and right are symmetrical, the nearest point effect is better; when they are not symmetrical, use face interpolation.': '左右对称时最近点效果好，左右不对称时使用面插值',
    "Delete unused vertex groups (deformation bones, modifiers), excluding those used by other objects.": '删除没有使用的顶点组（形变骨骼，修改器），不包括被其他物体使用的顶点组',
    'Adjust the wave modifier': '调整波修改器',
    'WaveHelper': '波浪修改器',
    'Motion': '运动',
    'Along Normals': '沿法向',
    'Falloff': '衰减',
    'Vertex Groups': '顶点组',
    'Animation': '动画',
    'Total frame count for looping': '循环总帧数',
    'Total frame count for motion': '运动总帧数',
    'Frame Start': '起始帧',
    'Frame Zero': '归零帧',
    'Frame End': '结束帧',
    'Frame Stop': '停止帧',
    'Full stop frame': '完全停止帧',
    'Damping': '阻尼',
    'Offset': '偏移量',
    'Set loop animation': '设置循环动画',
    'Width': '波宽度',
    'Width of each wave': '每个波的宽度',
    'High precision': '高精度',
    'Wave spacing': '波间隔',
    'The spacing between each wave': '每个波之间的间隔',
    'Frequency': '频率',
    'In one second, the number of oscillations of particles, directly expressed as the reciprocal of the period': '一秒内，粒子的振动次数，直接表示为周期的倒数',
    'Direction': '方向',
    'Diffusion': '扩散',
    'Shrink': '收缩',

    'Default lattice resolution': '默认晶格分辨率',
    'Interpolation': '插值',
    'Mode': '模式',
    'Lattice Helper': '晶格助手',
    'Lattice overlay': '晶格覆盖',
    'Automatically add a lattice to selected objects': '自动为选中物体添加晶格',
    'Set parent': '设置父级',
    'If in Object Mode, set the lattice as the parent of the object.If in lattice Editing Mode, set the active object as the parent of the lattice': '如果在物体模式下,将设置晶格为物体的父级,如果在网格编辑模式下,将设置活动物体为晶格父级',
    'Set the active item as the parent of other selected objects': '设置活动项为其它选中物体父级',
    'entirety': '整体',
    'All selected vertices as a single entity': '所有选择顶点作为一个整体',
    'Bounding box': '边界框',
    'Selection block (edit mode)': '选择块(编辑模式)',
    'Entire block (edit mode)': '整个块(编辑模式)',
    'Add a lattice for each selected block as a separate region within edit mode': '将编辑模式内每一个选择的块作为单独的一个区域添加一个晶格',
    'Add a lattice for all selected blocks within edit mode as a single region': '将编辑模式内所有选择的块作为一个区域添加晶格',
    'Specify a vertex group for the modifier': '为修改器指定顶点组',
    'Generate a vertex group based on the selected mode': '根据所选的模式生成顶点组',
    'All selected objects as a single entity': '所有选择物体作为一个整体',
    'Use the bounding box of each selected object as a separate lattice': '以每一个选择物体的边界框作为一个单独的晶格',
    'Objects without selection to add lattices': '未选择可添加晶格物体',
    'Apply lattice': '应用晶格',
    'Delete lattice': '删除晶格',
    'Automatically apply the lattice modifier': '自动应用晶格修改器',
    'Apply the lattice modifier': '应用晶格修改器',
    'Apply the lattice modifier as a shape key': '应用晶格修改器为形态键',
    'Save the lattice modifier as a shape key': '保存晶格修改器为形态键',
    'Delete the lattice modifier': '删除晶格修改器',
    'Delete the lattice': '删除晶格',
    'When applying or deleting the lattice modifier, remove the specified lattice for the selected lattice or selected objects': '在应用或删除晶格修改器时,删除所选晶格或所选物体所设修改器指定晶格',
    'Delete the used vertex group': '删除使用的顶点组',
    'Delete the vertex group used by the lattice modifier, and simultaneously remove the vertex group used by the lattice modifier when applying or deleting it': '删除晶格修改器使用的顶点组,在应用或删除晶格修改器时同时删除晶格修改器所使用的顶点组',
    'skip applying the modifier': '跳过应用修改器',
    'type not supported for applying lattice modifier': '类型不支持应用晶格修改器',

    "Show Toggle Bend Axis Gizmo": "显示切换弯曲轴向Gizmo",
    "AIGODLIKE Community:小萌新": "AIGODLIKE社区,小萌新",
    "AIGODLIKE": "辣椒出品",
    "Gizmo Property Show Location": "Gizmo属性显示位置",
    "You can press the following shortcut keys when dragging values":
        "拖动值时可以按以下快捷键",
    "    Wheel:   Switch Origin Ctrl Mode":
        "    滚轮:   切换原点控制模式",
    "    X,Y,Z:  Switch Modifier Deform Axis":
        "    X,Y,Z:  切换修改器型变轴",
    "    W:       Switch Deform Wireframe Show":
        "    W:       切换形变线框显示",

    "    A:       Switch To Select Bend Axis Mode(deform_method=='BEND')":
        "    A:       切换到选择弯曲轴模式(形变方法='弯曲')",
    "Show Set Axis Button": "显示设置轴向Gizmo",
    "Follow Upper Limit(Red)": "跟随上限(红色)",
    "Follow Lower Limit(Green)": "跟随下限(绿色)",
    "Lower limit(Green)": "下限(绿色)",
    "UP Limits(Red)": "上限(红色)",
    "Show Deform Wireframe": "显示形变线框",

    "Minimum value between upper and lower limits": "上限与下限之间的最小值",
    "Upper and lower limit tolerance": "上下限容差",

    "Draw Upper and lower limit Bound Box Color": "绘制网格上限下限边界线框的颜色",
    "Upper and lower limit Bound Box Color": "上限下限边界框颜色",
    "Draw Bound Box Color": "绘制网格边界框的颜色",
    "Bound Box": "边界框颜色",
    "Draw Deform Wireframe Color": "绘制网格形变形状线框的颜色",
    "Deform Wireframe": "形变线框颜色",

    "Simple Deform visualization adjustment tool": "简易形变可视化工具",

    "Select an object and the active modifier is Simple Deform":
        "选择物体并且活动修改器为简易形变",
    "Bound Middle": "边界框中心",
    origin_text(not_add, "as the lower limit"):
        "添加一个空物体原点作为旋转轴(如果已有原点则不添加),并在操作时设置原点位置为下限位置",
    origin_text(not_add, "as the upper limit"):
        "添加一个空物体原点作为旋转轴(如果已有原点则不添加),并在操作时设置原点位置为上限位置",
    origin_text("it will not be added",
                "between the upper and lower limits"):
        "添加一个空物体原点作为旋转轴(如果已有原点则不添加),并在操作时设置原点位置为上下限之间的位置",
    origin_text(not_add,
                "as the position between the bounding boxes"):
        "添加一个空物体原点作为旋转轴(如果已有原点则不添加),并在操作时设置原点位置为边界框之间的位置",
    "No origin operation": "不进行原点操作",
    "Origin control mode": "原点控制模式",
    "Down limit": "下限",
    "Coefficient": "系数",
    "Up limit": "上限",
    "Upper limit": "上限",

    "3D View -> Select an object and the active modifier is simple "
    "deformation": "3D视图 -> 选择一个物体,"
                   "并且活动修改器为简易形修改器",

    "3D View: Simple Deform Helper": "3D 视图: Simple Deform Helper 简易形变助手",
    "Tool Options": "工具选项",
    "The scaling value of the object is not 1": "对象的缩放值不是1",

    "which will cause the deformation of the simple deformation "
    "modifier.": "这将导致简易形变修改器变形",
    "Please apply the scaling before deformation.": "请应用缩放",

    'Grid overlay': '网格覆盖',
    'Automatically add grid overlay to selected objects': '自动为选中物体添加网格覆盖',
    'Grid binding': '网格绑定',
    'Add grid modifier to a subset of this grid': '添加网格修改器到该网格的子集',
    'Apply deformation modifier': '应用形变修改器',
    'Automatically apply deformation modifier': '自动应用形变修改器',
    'Apply modifier': '应用修改器',
    'Apply modifier as a shape key': '应用修改器为形态键',
    'Save modifier as a shape key': '保存修改器为形态键',
    'Delete modifier': '删除修改器',
    'Delete the grid used by the deformation modifier': '删除形变修改器所使用网格',
    'When applying or deleting the modifier, remove the specified grid for the selected modifier or selected objects with a deformation modifier': '在应用或删除修改器时删除所选或所选物体所设形变修改器所指定的网格',
    'MeshDeformHelper': '网格形变助手',
    'Create convex hull': '创建凸包',



    "Smart Vert": '智能顶点',
    "Smart Vertex Merging, Connecting and Sliding": '智能顶点合并、连接和滑动',
    "Smart Edge Creation, Manipulation, Projection and Selection Conversion": '智能边缘创建、操作、投影和选择转换',
    "Smart Face": '智能面',
    "Smart Face Creation and Object-from-Face Creation": '智能面创建和从面创建物体',
    "Old Modifier": '老版修改器',
    "Enable Old Modifier": '启用老版修改器',
    "Mirror Vertex Group": '镜像顶点组',
    "Mirror Vg": '镜像顶点组',
    "Wave Modifier": '波浪修改器',
    "Meshdeform Helper": '网格形变助手',
    "Simple Deform Helper": '简易形变助手',
    "Convenient and Quick Grid Creation": '方便快捷创建晶格',
    "User-friendly Visual 3D Components": '好用的可视化的3d组件',
    "Quick Setup Mesh Deformation": '快速设置网格形变',
    "Improve Parameter Display for Wave Modifier": '为波浪修改器添加更好的参数显示',
    "Quick Geometry Clean-up": '快速几何清理',
    "Edge Constraint": '边缘约束',
    "Edge Constrained Rotation and Scaling": '边缘约束旋转和缩放',
    "PunchIt Manifold Extrusion and Cursor Spin": 'PunchIt流形挤出和光标旋转',
    "Focus": '聚焦',
    "Object Focus and Multi-Level Isolation": '物体聚焦和多级隔离',
    "Flick Object Mirroring and Un-Mirroring": '对象镜像与取消镜像',
    "Object per-axis Location, Rotation and Scale Alignment, as well as Object-Inbetween-Alignment": '物体按轴位置、旋转和比例对齐，以及物体之间的对齐',
    "Group Objects using Empties as Parents": '将对象分组，使用空物体作为父对象',
    "Smart Drive": '智能驱动',
    "Use one Object to drive another": '使用一个物体来驱动另一个物体',
    "Clipping Toggle": '裁剪切换',
    "Viewport Clipping Plane Toggle": '视口裁剪平面切换',
    "Mesh Cut": '网格切割',
    "Knife Intersect a Mesh-Object, using another one": '用另一个网格对象刀具相交一个网格对象',
    "Customize": '自定义',
    "Customize various Blender preferences, settings and keymaps": '自定义各种Blender首选项、设置和按键映射',
    "Modes Pie": '模式菜单',
    "Quick mode changing": '快速模式切换',
    "Save Pie": '保存菜单',
    "Save, Open, Append and Link. Load Recent, Previous and Next. Purge and Clean Out. ScreenCast and Versioned Startup file": '保存、打开、追加和链接。加载最近、上一个和下一个。清除和清理。录屏和版本化启动文件。',
    "Alignments Pie": '对齐菜单(面/uv)',
    "Edit mesh and UV alignments": '编辑网格和UV对齐',
    "Align Helper Pie": 'popoti对齐助手',
    "Align Pie": '对齐菜单(编辑模式/UV)',
    "Align Helper": 'popoti对齐助手',
    "Object Alignment Assistant": '物体对齐助手',
    "Cursor and Origin Pie": '光标原点菜单',
    "Cursor and Origin": '光标原点菜单',
    "Cursor and Origin manipulation": '光标和原点操作',
    "Collections Pie": '集合菜单',
    "Collection management": '集合管理',
    "Tools Pie": '工具菜单',
    "Switch Tools, useful with BoxCutter/HardOps and HyperCursor": '切换工具，与BoxCutter/HardOps和HyperCursor一起使用很有用',
    "Print Addon Registration Output in System Console": '在系统控制台中打印插件注册输出',
    "The Kourin_tool tool is a comprehensive Blender enhancement tool developed based on machine3Tools (GPL)": 'Kourin_tool工具是一款基于machine3Tools（GPL）开发的综合搅拌机增强工具',
    "Show Sidebar Panel": '显示侧边栏面板',
    "HUD Scale": 'HUD 比例',
    "Mirror Flick Distance": '镜像抖动距离',
    "Fade time": '淡入淡出时间',
    "Clean Up": '清理',
    "Select Hierarchy": '选择层次',
    "Viewport Tweening": '视口补间',
    "Ignore Lights (keep them always visible)": '忽略灯光（使它们始终可见）',
    "Sub Menu": '子菜单',
    "Use Group Sub Menu in Object Context Menu": '在对象上下文菜单中使用组子菜单',
    "Outliner Toggles": '大纲切换',
    "Remove Empty": '移除空物体',
    "Show Group Toggles in Outliner Header": '在大纲标题中显示组切换',
    "Automatically remove Empty Groups in each Cleanup Pass": '在每次清理过程中自动移除空组',
    "Auto Name": '自动命名',
    "Prefix": '前缀',
    "Suffix": '后缀',
    "Default Empty Draw Size": '默认空物体绘制大小',
    "Fade Sub Group Sizes": '淡化子组大小',
    "Factor": '系数',
    "Input & Navigation": '输入与导航',
    "Keymaps": '按键映射',
    "Startup": '启动',
    "Keymaps have been modified, restore them first.": '按键映射已被修改，请先恢复它们。',
    "Restore now": '立即恢复',
    "Toggle Cavity/Curvature OFF in Edit Mode, ON in Object Mode": '在编辑模式下关闭凹凸/曲率开关，在对象模式下打开',
    "Toggle X-Ray ON in Edit Mode, OFF in Object Mode, if Pass Through or Wireframe was enabled in Edit Mode": '在编辑模式下，如果启用了穿透或线框模式，则将 X 射线打开，在对象模式下关闭。',
    "Sync Tool if possible, when switching Modes": '在可能的情况下，切换模式时同步工具',
    "Import / Export": '导入/导出',
    "Show .obj Import/Export": '显示 .obj 导入/导出',
    "Show Plasticity Import/Export": '显示塑性导入/导出',
    ".obj import/export with Axes set up already": '已设置轴的 .obj 导入/导出',
    "Show .fbx Import/Export": '显示 .fbx 导入/导出',
    "Use 'Fbx All' for Applying Scale": '使用“Fbx All”来应用比例',
    "Show .usd Import/Export": '显示 .usd 导入/导出',
    "Show .stl Import/Export": '显示 .stl 导入/导出',
    "Screen Cast": '屏幕录制',
    "Show Screencast in Save Pie": '在保存pie中显示屏幕录制',
    "Operator Count": '操作符数量',
    "Font Size": '字体大小',
    "Highlight Operators from Kourin_tool addons": '突出显示来自 Kourin_tool 插件的操作符',
    "Display Operator's Addon": '显示操作符的插件',
    "Display Operator's bl_idname": '显示操作符的 bl_idname',
    "Use SKRIBE (dedicated, preferred)": '使用 SKRIBE（专用，首选）',
    "Use Screencast Keys (addon)": '使用 Screencast Keys（插件）',
    "Pre-Undo Save": '预撤销保存',
    "Make Pre-Undo Saving available in the Pie": '在饼图中提供预撤销保存',
    "Useful if you notice Undo causing crashes": '如果你注意到撤销导致崩溃，这将非常有用',
    "Versioned Startup File": '版本化的启动文件',
    "Use CTRL + U keymap override": '使用CTRL + U键映射覆盖',
    "npanel text": 'n面板文字',
    "Show Cursor and Selected to Grid": '显示光标和选定内容到网格',
    "Set Transform Preset when Setting Cursor": '设置光标时设置变换预设',
    "Show BoxCutter Presets": '显示 BoxCutter 预设',
    "Show Hard Ops Menu": '显示 Hard Ops 菜单',
    "Show Quick Favorites": '显示快速收藏',
    "Show Tool Bar": '显示工具栏',
    "No tools or pie menus with settings have been activated.": '未激活任何工具或带有设置的饼菜单。',
    "No keymappings available, because none of the tools have been activated.": '没有可用的按键映射，因为没有激活任何工具。',
    "No keymappings created, because none of the pies have been activated.": '因为没有激活任何饼菜单，所以没有创建按键映射。',
    "Merge Last": '合并最后',
    "Merge Center": '合并中心',
    "Merge Paths": '合并路径',
    "Connect Paths": '连接路径',
    "Slide Extend": '滑动延伸',
    "Smart Edge": '智能边缘',
    "Toggle Sharp/Weight": '切换锐边/权重',
    "Offset Edges": '偏移边缘',
    "View Selected": '查看所选',
    "Local View": '局部视图',
    "Local": '局部',
    "World": '世界',
    "Local View (Inverted)": '局部视图（反转）',
    "Flick Mirror": '快速镜像',
    "Object Mode": '对象模式',
    "Pose Mode": '姿势模式',
    "Open Filebrowser": '打开文件浏览器',
    "Open .blend File": '打开 .blend 文件',
    "Toggle Sorting": '切换排序',
    "Toggle Display": '切换显示',
    "Cycle Thumbs Forwards": '向前循环缩略图',
    "Cycle Thumbs Backwards": '向后循环缩略图',
    "Toggle Hidden": '切换隐藏',
    "Create Group": '创建组',
    "Select Group": '选择组',
    "Toggle Group Mode": '切换组模式',
    "Expand Outliner": '展开大纲',
    "Collapse Outliner": '折叠大纲',
    "Toggle Children": '切换子项',
    "Save, Open, Append": '保存,打开,附加',
    "Save Versioned Startup File": '保存版本化的启动文件',
    "Current file is unsaved. Start a new file anyway?": '当前文件未保存。仍然要开始新文件吗？',
    "Save the current file in the desired location\nALT: Save as Copy\nCTRL: Save as Asset": '将当前文件保存在所需位置\nALT：另存为副本\nCTRL：另存为资源',
    "Incremental Save": '增量保存',
    "Save unsaved file as...": '将未保存的文件另存为...',
    "Load most recently used .blend file": '加载最近使用的 .blend 文件',
    "Load Most Recent": '加载最近的',
    "Kourin_tool: Load previous file": 'Kourin_tool：加载上一个文件',
    "Kourin_tool: Load next file": 'Kourin_tool：加载下一个文件',
    "Open System's Temp Folder, which is used to Save Files on Quit, Auto Saves and Undo Saves": '打开系统的临时文件夹，该文件夹用于在退出时保存文件，自动保存和撤销保存',
    "Kourin_tool: Purge Orphans": 'Kourin_tool：清理孤立物',
    "Clean out .blend file!": '清理 .blend 文件！',
    "Clean out .blend": '清理 .blend 文件！',
    "Kourin_tool: Reload Linked Liraries": 'Kourin_tool：重新加载链接的库',
    "Kourin_tool: Screen Cast": 'Kourin_tool：屏幕录制',
    "Screen Cast Operators": '屏幕录制操作',
    "Screen Cast recent Operators and Keys": '屏幕录制最近的操作和按键',
    "Screen Cast Recent Operators": '最近的屏幕录制操作',
    "INFO: Enabling Screencast Keys Addon": '信息：启用屏幕录制按键插件',
    "turning skribe ON!": '打开 SKRIBE！',
    "Open Temp Dir": '打开临时目录',
    "(R) Most Recent": "(R) 最近的",
    "Import": '导入',
    "All Recent": '所有最近的',
    "Save As..": '另存为..',
    "Cursor Pie": '游标菜单',
    "Doubles": '重叠',
    "Redundant": '冗余',
    "Chamfer": '倒角',
    "Korean Bevel": '韩式斜边',
    "Bounds/Region": '范围/区域',
    "Edge Constrained {}": '边约束 {}',
    "Recalculate Normals": '重新计算法线',
    "Non-Manifold": '非流形',
    "Non-Planar": '非平面',
    "Tris": '三角',
    "Ignore Mirrors": '忽略镜像',
    "Drive it!": '添加驱动',
    "Group.": '打组',
    "Un-Group": '取消组',
    "Groupify": "分组化",
    "Duplicate Group": '复制组',
    "Add to Group": '添加到组',
    "Remove from Group": '从组删除',
    "Hide Empties": '隐藏空物体',
    "Recursive": '递归',
    "Auto Select": '自动选择',
    "Update": '更新',
    "Set Batch Pose": '设置批量姿势',
    "Set Pose": '设置姿势',
    "Alpha.": '透明度',
    "Poses": '姿势',
    "Group Gizmos": '组工具形状',
    "Adjust Group Origin": '调整组原点',
    "Disable, when done!": '完成后禁用',
    "Active Group": '活动组',
    "Global Group Gizmos": '显示全局gizmos',
    "3D View: POPOTI Align Helper": "3D 视图: POPOTI对齐助手",
    "POPOTI Align Helper": "POPOTI对齐助手",
    "World Original": "世界原点",
    "More friendly alignment based on observation perspective": "更友好的基于观察视角的对齐",
    "Tool Panel": "工具面板",
    "Axis to be aligned": "需要对齐的轴",
    "Select the axis to be aligned, multiple choices are allowed": "选择需要进行对齐的轴,可多选",
    "Align X Axis": "对齐X轴",
    "Align Y Axis": "对齐Y轴",
    "Align Z Axis": "对齐Z轴",
    "Min Point": "最小点",
    "Max Point": "最大点",
    "Center Align": "中心对齐",
    "Align to Min Point": "对齐到最小点",
    "Align to Max Point": "对齐到最大点",
    "Distribution": "分布",
    "Distribution Align": "分布对齐",
    "General alignment, you can set the alignment of each axis(maximum, center, minimum)": "常规对齐,可以设置每个轴的对齐方式(最大,居中,最小)",
    "Align to Cursor(Scale reset 1)": "对齐到游标(缩放将重置为1)",
    "Align to Active Object": "对齐到活动物体",
    "Aligning to the world origin is the same as resetting": "对齐到世界原点,和重置功能相同",
    "Sort distribution by X axis": "按X轴排序分布",
    "Sort distribution by Y axis": "按Y轴排序分布",
    "Sort distribution by Z axis": "按Z轴排序分布",
    "Align and sort the selected objects according to the selection axis to obtain the correct movement position": "按选择轴对所选物体进行对齐并排序,以获取正确的移动位置",
    "Distribution sort axis": "分布排序轴",
    "Lowest Object": "最低物体",
    "All Object": "所有物体",
    "Sort Axis": "排序轴",
    "Ground": "地面",
    "Align Ground": "对齐地面",
    "Adjustment": "调整",
    "Distribution interval value": "分布间隔距离",
    "Active": "活动项",
    "Not Selected Active Object": "未选择活动物体",
    "Fixed the nearest and farthest objects": "固定最远和最近的物体,按间距自动排列中间的物体",
    "Adjust the distance between each object(Fixed active object)": "调整每个对象之间的距离(固定活动对象位置)",
    "Show Button Text": "显示按钮文字",
    "Align To Ground Object": "对齐到地面物体",
    "To Object": "到物体",
    "History Unmirror": '历史取消镜像',
    "History Object": '历史对象',
    "Group Pose Matrix": '组姿势矩阵',
    "Remove Pose": '移除姿势',
    "Batch Pose": '批量姿势',
    "Toggle Connection to Other Batch Poses in this Group Hierarchy\n\nIf the active pose is disconnected, it will be retrieved like a regular single Pose.\nDisconnected Batch Poses in the Group Hierarchy below, will not be previewed, retrieved or removed, unless overriden in the Retrieve/Remove ops": '切换与此组层次结构中的其他批处理姿势的连接如果活动姿势未连接，它将像常规单个姿势一样被检索。在下面的组层次结构中，未连接的批处理姿势将不会被预览、检索或移除，除非在检索/移除操作中进行覆盖。',
    "Use Undo Save": '使用撤销保存',
    "Use Redo Save": '使用重做保存',
    "Save before Undoing\nBe warned, depending on your scene complexity, this can noticably affect your undo speed": '撤销前保存\n请注意，根据您的场景复杂性，这可能会显着影响您的撤销速度',
    "Also save before first Operator Redos": '在第一次操作重做之前也要保存',
    "Pass Through": '穿透',
    "Show Edit Mesh Wireframe": '显示编辑网格线框',
    "Sync Selection": '同步选择',
    "Eevee Preset": 'Eevee预设',
    "Eevee Quality Presets": 'Eevee质量预设',
    "Set Use Scene Lights": '设置使用场景灯光',
    "Set Use Scene Lights when changing Eevee Preset": '更改 Eevee 预设时，设置使用场景灯光',
    "Set Use Scene World": '设置使用场景环境',
    "Set Use Scene World when changing Eevee Preset": '更改 Eevee 预设时，设置使用场景环境',
    "Show Smart Drive": '显示智能驱动',
    "Driver Start Value": '驱动器起始值',
    "Driver End Value": '驱动器结束值',
    "Driver Axis": '驱动轴',
    "Driver Transform": '驱动器变换',
    "Driver Space": '驱动空间',
    "Driven Start Value": '被驱动起始值',
    "Driven End Value": '被驱动结束值',
    "Driven Axis": '被驱动轴',
    "Driven Transform": '被驱动变换',
    "Driven Lmit": '被驱动限制',
    "BoxCutter Orientation": '剖切工具方向',
    "Show Group": '显示组',
    "Show Group Gizmos": '显示组gizmos',
    "Show Group Gizmo": '显示组gizmos',
    "Toggle Group Gizmos Globally": '全局切换组控件',
    "Auto Select Groups": '自动选择组',
    "Automatically select the entire Group, when its Empty is made active": '当其空物体激活时自动选择整个组',
    "Recursively Select Groups": '递归选择组',
    "Recursively select entire Group Hierarchies down": '递归向下选择整个组层次结构',
    "Hide Group Empties in 3D View": '在3D视图中隐藏组空对象',
    "Hide Group Empties in 3D View to avoid Clutter": "在3D视图中隐藏组空物体以避免杂乱",
    "Show Auto Select Toggle in main Object Context Menu": "在主对象上下文菜单中显示自动选择切换",
    "Show Recursive Selection Toggle in main Object Context Menu": "在主对象上下文菜单中显示递归选择切换",
    "Show Group Hide Toggle in main Object Context Menu": "在主对象上下文菜单中显示组隐藏切换",
    "Transform only the Group Origin(Empty)": '仅变换组原点（空物体）',
    'Transform the Group Origin(Empty) only, disable Group Auto-Select and enable "affect Parents only"': '仅变换组原点（空物体），禁用组自动选择，并启用"仅影响父级"',
    "Global Group Gizmo Size": '全局组控件大小',
    "Show Assetbrowser Tools": '显示资源浏览器工具',
    "show X rotation gizmo": "显示X轴旋转控件",
    "show Y rotation gizmo": "显示Y轴旋转控件",
    "show Z rotation gizmo": "显示Z轴旋转控件",
    "group gizmo size": '组控件大小',
    "Group Rest Post Matrix": '群组静止状态后的矩阵',
    "Double Click to Rename": '双击重命名',
    "Pose Preview Alpha": '姿势预览透明度',
    "Alpha used to preview Poses across the entire Group": '用于预览整个组中姿势的 Alpha 值',
    "Draw a Preview of the Active Pose": '绘制活动姿势的预览',
    "Smooth Angle": '平滑角度',
    "Has been smoothed": '已经平滑处理',
    "Draw Axes": '绘制坐标轴',
    "Active Object Bevel Toggle": '活动对象倒角切换',
    "Toggle Bevel Shader on Active Object": '切换活动对象上的倒角着色器',
    "Factor to modulate the Bevel Shader Radius on the Active Object": '用于调节活动对象上倒角着色器半径的因子',
    "Active Object Bevel Radius Modulation": '活动对象倒角半径调制',
    "Hash to find associated objects": '用于查找关联对象的哈希值',
    "Group Objects by Parenting them to an Empty": "通过将它们作为空物体的子物体进行分组",
    "Un-Group selected top-level Groups\nALT: Un-Group all selected Groups": '取消对所选顶级组的分组\nALT:取消对所有所选组的分组',
    "Un-Group selected top-level Groups\nALT: Un-Group all selected Groups\nCTRL: Un-Group entire Hierarchy down": '取消对所选顶级组的分组\nALT：取消对所有所选组的分组\nCTRL：取消对整个层次结构向下的分组',
    "Un-Group selected top-level Groups ALT: Un-Group all selected Groups CTRL: Un-Group entire Hierarchy down": '取消对所选顶级组的分组\nALT：取消对所有所选组的分组\nCTRL：取消对整个层次结构向下的分组',
    "Un-Group selected top-level Groups": '取消对所选顶级组的分组',
    "All Selected": '全部选中',
    "Entire Hierarchy": '整个层次结构',
    "Turn any Empty Hirearchy into Group": "将任何空物体层次结构转换为组",
    "Select Group\nCTRL: Select entire Group Hierarchy down": '选择组\nCTRL：选择整个组层次结构向下',
    "Select entire Group Hierarchies down": "选择整个组层次结构向下",
    "Select Top Level Groups\nCTRL: Select entire Group Hierarchy down": "选择顶级组\nCTRL：选择整个组层次结构向下",
    "Duplicate entire Group Hierarchies down\nALT: Create Instances": "复制整个组层次结构向下\nALT：创建实例",
    "Duplicate Top Level Groups\nALT: Create Instances\nCTRL: Duplicate entire Group Hierarchies down": "复制顶级组\nALT：创建实例\nCTRL：复制整个组层次结构向下",
    "Add Selection to Group": '将选定内容添加到组中',
    "Re-Align Group Empty": '重新对齐组空物体',
    "Add Mirror Modifiers, if there are common ones among the existing Group's objects, that are missing from the new Objects": "如果现有组对象中存在的常见镜像修饰符在新对象中缺失，则添加镜像修饰符",
    "Add Object Color, from Group's Empty": "从组的空物体添加对象颜色",
    "Remove Selection from Group": '从组中移除选中',
    "Transform Group": '变换组',
    "Recall Pose + Finish": '撤销姿势 + 完成',
    "Select Group Empty": '选择组的空物体',
    "Setup Group Gizmos": '设置组控件',
    "Setup Group Gizmos ": '设置组控件',
    "5° Angle Snap": '5° 角度捕捉',
    "Set Pose + Finish": '设置姿势 + 完成',
    "Mark Pose for Removal": '标记姿势以移除',
    "Mark All Poses for Removal": '标记所有姿势以移除',
    "Rotate Group": '旋转组',
    " around ": '围绕',
    "Angle: ": '角度：',
    "Snapping": '捕捉',
    "Set Global Size to 1, and compensate each Group's Size accordingly.": "将全局大小设置为1，并相应地补偿每个组的大小。",
    "Toggle All": '切换全部',
    " Disabled": '已禁用',
    "Axes: ": '坐标轴：',
    "Size: ": '大小：',
    "Lock Rotational Axes ": '锁定旋转轴',
    "(those without Gizmos)": '那些没有控件的',
    "Set Group Pose": '设置组姿势',
    "Update active Pose from current Group Empty Rotation": '从当前组空物体的旋转更新活动姿势',
    "Retrieve Selected Group Pose": '检索所选组姿势',
    "Batch Retrieval": '批量检索',
    "Retrieve Up": '向上检索',
    "Retrieve Poses Up the Hierarchy too": '也向上检索层次结构中的姿势',
    "Retrieve Unlinked": '检索未链接的',
    "Retrieve Poses, that have been unlinked too": '检索已取消链接的姿势',
    "Remove related Batch Poses": '移除相关的批处理姿势',
    "Remove Up": '向上移除',
    "Remove Disconnected": '移除断开连接的',
    "Remove all related Batch Poses in the Group Hierarchy": '移除组层次结构中的所有相关批处理姿势',
    "Remove Batch Poses further Up the Hierarchy too": '也移除层次结构中更高级别的批处理姿势',
    "Remove Batch Poses, that have been unlinked too": '移除已取消链接的批处理姿势',
    "Batch Poses to be Removed:": '待移除的批处理姿势：',
    "Drive one Object using another": '使用另一个对象驱动一个对象',
    "Kourin_tool: Bake Group Gizmo Size":"Kourin_tool: 烘焙组控件大小",
    "Kourin_tool: Retrieve Group Pose": "Kourin_tool: 检索组姿势",
    "Kourin_tool: Sort Group Pose":"Kourin_tool: 排序组姿势",
    "Move Selected Group Pose {}": '移动所选组姿势{}',
    "Kourin_tool: Remove Group Pose": "Kourin_tool: 移除组姿势",
    "Local Space Align\nALT: World Space Align\nCTRL: Cursor Space Align": "本地空间对齐\nALT: 世界空间对齐\nCTRL: 光标空间对齐",
    "Straighten verts or edges": '打直顶点或边',
    "Straighten": '打直',
    "Local Space Center\nALT: World Space Center\nCTRL: Cursor Space Center":"本地空间中心\nALT: 世界空间中心\nCTRL: 光标空间中心",
    "Align verts based on min/max UV values": "基于最小/最大UV值对顶点进行对齐",
    "Set Tool by Name": "按名称设置工具",
    "Remove empty Collections": "移除空集合",
    "Select Collection Objects\nSHIFT: Select all Collection Objects\nALT: Deselect Collection Objects\nSHIFT+ALT: Deselect all Collection Objects\nCTRL: Toggle Viewport Selection of Collection Objects": "选择集合对象\nSHIFT：选择所有集合对象\nALT：取消选择集合对象\nSHIFT+ALT：取消选择所有集合对象\nCTRL：切换视口选择集合对象",
    "Create Collection": "创建集合",
    "Create": '创建',
    "Remove Selection from a Collection":"从集合中移除所选内容",
    "Remove from": '移除',
    "Add to": '添加',
    "Move to": '移动',
    "Scene Collections (Selection)": "场景集合（选择）",
    "Scene Collections": '场景集合',
    "Set Selected Objects' Origin to Active Object\nALT: only set Origin Location\nCTRL: only set Origin Rotation": "将所选对象的原点设置为活动对象\nALT：仅设置原点位置\nCTRL：仅设置原点旋转",
    "Set Mesh Object's Origin to Active Vert/Edge/Face\nALT: only set Origin Location\nCTRL: only set Origin Rotation": "将网格对象的原点设置为活动顶点/边缘/面\nALT：仅设置原点位置\nCTRL：仅设置原点旋转",
    "Transform Selected Objects to Cursor\nALT: Only set Location\nCTRL: Only set Rotation": "将所选对象转换到光标位置\nALT：仅设置位置\nCTRL：仅设置旋转",
    "Reset Cursor to World Origin\nALT: Only reset Cursor Location\nCTRL: Only reset Cursor Rotation": "将光标重置到世界原点\nALT：仅重置光标位置\nCTRL：仅重置光标旋转",
    "Invalid Modifier Keys": '无效按键',
    "Align Cursor with Selected Object(s)\nALT: Only set Cursor Location\nCTRL: Only set Cursor Rotation": "将光标与所选对象对齐\nALT：仅设置光标位置\nCTRL：仅设置光标旋转",
    "Align Cursor with Vert/Edge/Face\nALT: Only set Cursor Location\nCTRL: Only set Cursor Rotation": "将光标与顶点/边缘/面对齐\nALT：仅设置光标位置\nCTRL：仅设置光标旋转",
    f"{desc}": '将对象原点设置为边界框底部中心\nALT：基于评估后的网格确定底部中心，考虑到修饰器',
    "Set Selected Objects' Origin to Cursor\nALT: only set Origin Location\nCTRL: only set Origin Rotation": "将所选对象的原点设置为光标位置\nALT：仅设置原点位置\nCTRL：仅设置原点旋转",
    "Set Mesh Object's Origin to Cursor\nALT: only set Origin Location\nCTRL: only set Origin Rotation": "将网格对象的原点设置为光标位置\nALT：仅设置原点位置\nCTRL：仅设置原点旋转",
    "to Origin": '到原点',
    "to Cursor, Offset": '到游标,偏移',
    "to Grid": '到网格',
    "to Selected": '到选择',
    "to Cursor": '到游标',
    "to Geometry": '到几何体',
    "to Active": '到激活',
    "to Bottom": '到底部',
    "Start new .blend file": "开始新的 .blend 文件",
    "Surface Draw, create parented, empty GreasePencil object and enter DRAW mode.\nSHIFT: Select the Line tool.": "表面绘制，创建已设置父级的空涂鸦笔对象，并进入绘制模式。\nSHIFT：选择线条工具。",
    "Kourin_tool: Surface Draw Mode": 'Kourin_tool：表面绘制模式',
    "Versioned Startup File saved: {}": "已保存版本化的启动文件: {}",
    "Initial Startup File saved": "初始启动文件已保存",
    "Direct": '直接',
    "Proximity": '接近',
    "Intersection": '交叉',
    "Plane Intersection": "平面交叉",
    "Projected Plane Intersection": "投影平面交叉",
    "Direct Plane Intersection": '直接平面交叉',
    "MouseDir Plane Intersection": '鼠标方向平面交叉',
    "Mousedir Plane Intersection": '鼠标方向平面交叉',
    "Un-Mirror": "取消镜像",
    "Multiple": '多重',
    "Mirror across Cursor": "以光标为中心镜像",
    "Use Mislinged Object Removal": "使用未对齐对象移除",
    "Use existing Cursor Empty": "使用现有的光标空对象",
    "ROTATE {}": '旋转{}',
    "ROTATE {:.1f}": '旋转 {:.1f}',
    "Adjacent": '相邻',
    "Direction Locked": '方向锁定',
    "SCALE {:.2f}": '缩放 {:.2f}',
    "ZERO SCALE": '零缩放',
    "Zero Scale": '零缩放',
    "Constrain Mode": '约束模式',
    "Direction Lock": '方向锁定',
    "Align Ends: {}": '对齐末端：{}',
    "LOCAL {}": '局部 {}',
    "Face Alignment: {}": '面对齐 {}',
    "Individual Origins": '各自的原点',
    "Illegal Sellection": '非法选择',
    "Individual Origins: {}": '各自原点: {}',
    "Select one object first, then select the object to be cut last!": '先选择一个对象，然后再选择要切割的对象！',
    "Removes the last modifer in the stack of the selected objects": "移除所选对象堆栈中的最后一个修饰符",
    "Cut a Mesh Object, using another Object.\nALT: Flatten Target Object's Modifier Stack\nSHIFT: Mark Seams": "使用另一个对象剪切网格对象。\nALT：展平目标对象的修改器堆栈\nSHIFT：标记缝隙",
    "Invalid Property Combination": '无效的属性组合',
    "You can't combine {} with {}!": '你不能将 {} 和 {} 结合使用！',
    "Percentage of Segments fading into inner Diameter": '内径渐变段的百分比',
    "Depth in Percentage of minor Diameter": '小直径的百分比深度',
    "Crest": '尖端',
    "Bottom Flank": '底部侧面',
    "Top Flank": '顶部侧面',
    "Add Thread": '添加螺纹',
    "Toggle Object Outlines": '切换对象轮廓线',
    "Stats": '统计信息',
    "(Q) Outline": '(Q) 轮廓',
    "(V) Curvature": '(V) 曲率',
    "Overlays": '覆盖层',
    "(L) Solid": '(L) 实体',
    "Material": '材质',
    "Rendered": '渲染',
    "Auto Smooth Angle": '自动平滑角度',
    "Auto Smooth Angle: None": '自动平滑角度：无',
    "(N) Clear Custom Normals": '(N) 清除自定义法线',
    "Colorize Materials": '着色材质',
    "Autosmooth": '自动平滑',
    "Auto Smooth": '自动平滑',
    "Auto Smooth Angle Presets shown in the Shading Pie as buttons": "在着色饼中显示为按钮的自动平滑角度预设",
    "Shading Pie": '着色菜单',
    "Remove existing 'Auto Smooth' modifier": "移除现有的 '自动平滑' 修饰器",
    "Add 'Auto Smooth' modifier to smooth shade object angle based": "将 '自动平滑' 修饰器添加到基于角度的平滑阴影对象中",
    "Toggle mesh's Auto Smooth property": "切换网格的自动平滑属性",
    "Auto Smooth Angle Preset: {}": '自动平滑角度预设: {}',
    "\nALT: Mark MESH object edges sharp if face angle > auto smooth angle": '\nALT：如果面角度大于自动平滑角度，则标记 MESH 对象边缘为尖锐',
    "\nALT: Clear MESH object sharps, bweights, creases and seams": '\nALT：清除 MESH 对象的尖锐边缘、权重、折痕和缝隙',
    "\n\nSHIFT: Include Children": '\n\nSHIFT：包括子对象',
    "\nCTRL: Include Boolean Objects": '\nCTRL：包括布尔对象',
    "Avoid HyperCursor's Edge Bevels": '避免 HyperCursor 的边缘倒角',
    "Disabled Auto Smooth": '禁用自动平滑',
    "Enabled Auto Smooth": '启用自动平滑',
    "Enabled Auto Smooth with angle {}": '使用角度 {} 启用了自动平滑',
    "(incl. on Instances)": '（包括实例）',
    "Toggle Auto Smooth": '切换自动平滑',
    "Cleared {} Edges": '清除了 {} 边',
    "Marked Edges Sharp {}based on Angle {}": '基于角度 {} 标记了 {} 边缘为尖锐',
    "additively ": '叠加地',
    "Disabled Auto Smooth on {} Objects": '禁用了 {} 对象上的自动平滑',
    "Enabled Auto Smooth on {} Objects carrying Boolean Mods": '已启用了带有布尔修饰器的 {} 个对象的自动平滑',
    " + {} Boolean Mod Objects": '+{}个布尔修饰器对象',
    "+ {} recursive Children": '+{} 个递归子对象',
    "{} Shaded {} selected Objects": '{} 个已选择的对象 {} 着色',
    "Avoid Clearing SubD Creases": '避免清除次级细分折痕',
    "Clear Sharps, BWeights, Creases or Seams": '清除尖锐边、权重、折痕或缝隙',
    "Show Overlays in Solid Shading by default": '默认情况下在实体着色中显示叠加效果',
    "Show Overlays in Material Shading by default": '默认情况下在材质着色中显示叠加效果',
    "Show Overlays in Rendered Shading by default": '默认情况下在渲染着色中显示叠加效果',
    "For a newly created scene, or a .blend file where where it wasn't set before, show Overlays for Solid shaded 3D views": '对于新创建的场景，或者之前没有设置的 .blend 文件，在实体着色的 3D 视图中显示叠加效果',
    "For a newly created scene, or a .blend file where where it wasn't set before, show Overlays for Material shaded 3D views": '对于新创建的场景，或者之前未设置的 .blend 文件，在材质着色的 3D 视图中显示叠加效果',
    "For a newly created scene, or a .blend file where where it wasn't set before, show Overlays for Rendered shaded 3D views": '对于新创建的场景，或者之前未设置的 .blend 文件，在渲染着色的 3D 视图中显示叠加效果',
    "For a newly created scene, or a .blend file where where it wasn't set before, show Overlays for Wire shaded 3D views": '对于新创建的场景，或者之前未设置的 .blend 文件，在线框着色的 3D 视图中显示叠加效果',
    "Show Overlays in Wire Shading by default": '默认情况下在线框着色中显示叠加效果',
    "Toggle Curvature": '切换曲率',
    "Toggle Curvature (Edge Highlighting)": '切换曲率（边缘高亮）',
    "Matcap Switch": 'Matcap 切换',
    "Quickly Switch between two Matcaps": '快速切换两种 Matcap',
    "Toggle Grid": '切换网格',
    "Toggle Grid, distinguish between the grid in regular views and orthographic side views": '切换网格，在普通视图和正交侧视图之间区分',
    "Toggle Cavity": '切换Cavity',
    "Toggle Cavity (Screen Space Ambient Occlusion)": '切换凹陷（屏幕空间环境光遮蔽）',
    "Toggle Outline": '切换轮廓线',
    "WARNING: Object {} could no longer be found": '警告：找不到对象 {} ',
    "{} Overlays for {} Shading": '{} 叠加效果，适用于 {} 着色',
    "Switch to {} shading, and restore previously set Overlay Visibility": '切换到 {} 着色，并恢复先前设置的叠加效果可见性',
    "Kourin_tool: Switch Shading": 'Kourin_tool：切换着色',
    "Kourin_tool: Rotate Studiolight": 'Kourin_tool: 旋转灯光',
    "Rotate Studio Light by {} degrees\nALT: Rotate visible lights too": '旋转 {} 度的工作室灯光\nALT: 也旋转可见灯光',
    "Kourin_tool: Add World": '添加世界环境',
    "Kourin_tool: Adjust Bevel Radius": '调整倒角半径',
    "\n{} {} Bevel Radius": '\n{} {} 倒角半径',
    "\nSHIFT: {} {} Bevel Radius": '\nSHIFT: {} {} 倒角半径',
    "Toggle Wireframe": '切换线框',
    "Toggle Wireframe display for the selected objects\nNothing Selected: Toggle Wireframe Overlay, affecting all objects": '切换所选对象的线框显示\n未选择对象：切换线框叠加显示，影响所有对象',
    "Toggle X-Ray, resembling how edit mode wireframes worked in Blender 2.79": '切换X射线，类似于Blender 2.79中编辑模式下线框显示的方式',
    "Kourin_tool: Colorize Materials": 'Kourin_tool：着色材质',
    "Set Material Viewport Colors from last Node in Material": '从材质中的最后一个节点设置视口颜色',
    "Kourin_tool: Colorize Objects from Materials": 'Kourin_tool：从材质着色对象',
    "Set Object Viewport Colors of selected Objects from their active Materials": '将所选对象的对象视口颜色从其活动材质中设置',
    "Kourin_tool: Colorize Objects from Active": 'Kourin_tool：从活动对象着色对象',
    "Set Object Viewport Colors from Active Object": '从活动对象设置对象视口颜色',
    "Kourin_tool: Colorize Objects from Collections": 'Kourin_tool：从收藏着色对象',
    "Set Object Viewport Colors of selected Objects based on Collections": '基于收藏设置所选对象的对象视口颜色',
    "Multi-Collection Objects": '多收藏对象',
    "Decal Collections": '贴花收藏',
    "Assigned {} unique colors.": '分配了 {} 种独特的颜色。',
    "Kourin_tool: Colorize Objects from Groups": 'Kourin_tool：从组着色对象',
    "Recursively Set Random Object Viewport Colors for Group Objects based on Group Membership\nALT: Set Group Member Colors based on existing Group Empy Colors\nCTRL: Only Colorize the Active Group": '递归地根据组成员身份为组对象设置随机的对象视口颜色\nALT：根据现有的组空颜色设置组成员的颜色\nCTRL：仅着色活动组',
    "Recursively Set Random Object Viewport Colors for Group Objects based on Group Membership\nALT: Set Group Member Colors based on existing Group Empy Colors": '递归地根据组成员身份为组对象设置随机的对象视口颜色\nALT：根据现有的组空颜色设置组成员的颜色',
    "(X) Matcap Switch": '(X) Matcap 切换',
    "Matcap Flip": 'Matcap 翻转',
    "Use Flat Shadows": '使用平面阴影',
    "Use Shadows when in Flat Lighting": "在平面照明下使用阴影",
    "Use Scene Lights, Ambient Occlusion and Screen Space Reflections": '使用场景灯光、环境光遮蔽和屏幕空间反射',
    "Use Bloom and Screen Space Refractions": '使用泛光和屏幕空间折射',
    "Use Scene World and Volumetrics.\nCreate Principled Volume node if necessary": '使用场景世界和体积光。\n如果需要，创建主体积节点',
    "Choose Local or World space based on whether driver object is parented": '基于驱动对象是否被父物体化，选择局部或世界空间',
    "Add to Scene Collection": '添加到场景集合',
    "Add to Object Collections": '添加到物体集合',
    "Use Viewport Compositing": '使用视口合成',
    "Wireframe Color Type:": '线框颜色类型:',
    "Show object color on wireframe": '显示线框时对象颜色',
    "Draw Axes Size": '绘制坐标轴大小',
    "Draw Axes Alpha": '绘制坐标轴透明度',
    "Draw Axes in Screen Space": '在屏幕空间绘制坐标轴',
    "Draw Active's Object Axes": '绘制活动对象的坐标轴',
    "Draw Cursor's Axes": '绘制光标的坐标轴',
    "Render Engine": '渲染引擎',
    "Render Device": '渲染驱动',
    "Lighting Method": '照明方法',
    "Lighting Method for Solid/Texture Viewport Shading": '固体/纹理视口着色的照明方法',
    "Adjust Lights when Rendering": '渲染过程中调整光源',
    "Adjust Lights Area Lights when Rendering, to better match Eevee and Cycles": '渲染过程中调整面光源,以更好地匹配 Eevee 和 Cycles',
    "Divider used to calculate Cycles Light Strength from Eeeve Light Strength": '用于从 Eevee 光强计算 Cycles 光强的除数',
    "Last Light Adjustment": '最后的光照调整',
    "Have Lights been decreased by the init render handler?": '渲染初始化处理器是否已降低了光源强度?',
    "Enforce hide_render setting when Viewport Rendering": '在视口渲染时强制执行 hide_render 设置',
    "Enfore hide_render setting for objects when Viewport Rendering": '在视口渲染时对物体强制执行 hide_render 设置',
    "Batch Apply Bevel Shader to visible Materials": '批量将倒角着色器应用到可见材质上',
    "Use Bevel Shader": '使用倒角着色器',
    "Consider Object Dimensions for Bevel Radius Modulation": '考虑物体尺寸调节倒角半径',
    "Samples": '采样',
    "Bevel Shader Samples": '倒角着色器采样',
    "Radius": '半径',
    "Bevel Shader Global Radius": '倒角着色器全局半径',
    "Custom Local Views": '自定义本地视图',
    "Custom Cursor Views": '自定义游标视图',
    "Use Custom Views, based on the active object's orientation": '根据当前选中物体的朝向使用自定义视图',
    "Use Custom Views, based on the cursor's orientation": '根据游标的朝向使用自定义视图',
    "Align Mode": '对齐模式',
    "Background Strength": '背景强度',
    "View Axis": '视图轴',
    "Align Custom View to Active Object\nALT: Align View to Active %s": '将自定义视图对准活动对象\nALT：将视图对准活动%s',
    "Align Custom View to Cursor\nALT: Align View to Active %s": "将自定义视图对准光标\nALT：将视图对准活动%s",
    "Align View to World\nALT: Align View to Active to Active %s": '将视图对准世界\nALT：将视图对准活动%s',
    "Verts": '顶点',
    "Smart View Cam": '智能视图相机',
    "Default: View Active Scene Camera\nNo Camera in the Scene: Create Camera from View\nCamera Selected: Make Selected Camera active and view it.\nAlt + Click: Create Camera from current View.": '默认：查看活动场景相机\n场景中没有相机：从视图创建相机\n选择了相机：激活选定的相机并查看它。\n按住Alt键 + 单击：从当前视图创建相机。',
    "Make Active": '设为活动',
    "Make selected Camera active.": '将选中的相机设为活动相机。',
    "Kourin_tool: Next Cam": '下一相机',
    "Kourin_tool: Toggle Camera Perspective/Ortho": '切换相机为透视/正交投影',
    "Toggle Active Scene Camera Perspective/Ortho": '切换当前场景相机为透视/正交投影',
    "Kourin_tool: Toggle View Perspective/Ortho": '切换视图为透视/正交投影',
    "Toggle Viewport Perspective/Ortho": '切换视口为透视/正交投影',
    "Kourin_tool: Toggle Orbit Method": '切换轨道方式',
    "Change Orbit Method from Turntable to Trackball": '将旋转方式从旋转台切换到轨迹球',
    "Change Orbit Method from Trackball to Turntable": '将旋转方式从轨迹球切换到旋转台',
    "Turntable": '旋转台',
    "Kourin_tool: Toggle Orbit Selection": '切换旋转选择',
    "Disable Orbit around Selection": '禁用围绕选择物体旋转',
    "Enable Orbit around Selection": '启用围绕选择物体旋转',
    "Kourin_tool: Reset Viewport": '重置视口',
    "Perfectly align the viewport with the Y axis, looking into Y+": '将视口完美对齐到Y轴,朝向Y+方向',
    "Orthographic": '正交投影',
    "Perspective": '透视投影',
    "Reset Viewport": '重置视口',
    "Custom Views": '自定义视图',
    "(Q) Previous Cam": '(Q) 上一相机',
    "(W) Next Cam": '(W) 下一相机',
    "Cam to view": '将相机对准视图',
    "Unlock from View": '从视图中解锁',
    "Lock to View": '锁定到视图',
    "Front": '前',
    "Orbit Selection": '围绕选择对象轨道',
    "Viewport and Cameras": '视口和相机',
    "to {}": '到 {}',
    "Vert": '点',
    "Face": '面',
    "Object Origin": '物体原点',
    "Clean Up HUD Fade Time (seconds)": '清理HUD渐隐时间(秒)',
    "Select Hierarchy HUD Fade Time (seconds)": '选择层级HUD渐隐时间(秒)',
    "Clipping Toggle HUD Fade Time (seconds)": '裁剪指示器HUD渐隐时间(秒)',
    "Group HUD Fade Time (seconds)": '组HUD渐隐时间(秒)',
    "Tools Pie HUD Fade Time (seconds)": '工具菜单HUD渐隐时间(秒)',
    "Flick Distance": '快速移动距离',
    "Select Center Objects, Select/Hide Wire Objects, Select Hierarchy": '选择中心对象、选择/隐藏网格对象、选择层级',
    "Easily turn Cylinder Faces into Thread": '将圆柱面容易转换为螺纹',
    "Filebrowser Tools": '文件浏览器工具',
    "Additional Tools/Shortcuts for the Filebrowser (and Assetbrowser)": '文件浏览器(和资产浏览器)的其他工具/快捷键',
    "Views Pie": '视图菜单',
    "Control views. Create and manage cameras": '控制视图。创建和管理相机。',
    "Select Children": '选择子级',
    "Select Children (incl.)": '选择子级(含自身)',
    "Select Children (unhide)": '选择子级（取消隐藏）',
    "Select Children (incl. + unhide)": '选择子级（含自身 + 取消隐藏）',
    "Select Parents": '选择父级',
    "Select Parents (incl.)": '选择父级（含自身）',
    "Select Parents (unhide)": '选择父级（取消隐藏）',
    "Select Parents (incl. + unhide)": '选择父级（含自身 + 取消隐藏）',
    "Kourin_tool: Select Center Objects": 'Kourin_tool:选择中心物体',
    "Selects Objects in the Center, objects, that have verts on both sides of the X, Y or Z axis.": '选择中心对象，即在 X、Y 或 Z 轴两侧都有顶点的对象。',
    "Kourin_tool: Select Wire Objects": '选择线框对象',
    "Select Objects set to WIRE display type\nALT: Hide Objects\nCLTR: Include Empties": '选择显示类型设置为线框的对象\nALT：隐藏对象\nCTRL：包括空物体',
    "Kourin_tool: Select Hierarchy": 'Kourin_tool:选择层级',
    "Select Hierarchy Down": '选择层级下方',
    "Hierarchy Direction": '层级方向',
    "Include Selection": '包括选择',
    "Include Current Selection": '包括当前选择',
    "Include Mod Objects": '包括修改器对象',
    "Include Mod Objects, even if they aren't parented": '包括修改器对象,即使它们未被父子关联',
    "Unhide + Select": '取消隐藏并选择',
    "Unhide and Select hidden Children/Parents, if you encounter them": '取消隐藏并选择遇到的隐藏子级/父级',
    "Select Recursive Children": '递归选择子级',
    "Select Children Recursively": '递归选择子级',
    "Select Recursive Parents": '递归选择父级',
    "Select Parents Recursively": '递归选择父级',
    "with {} Hidden Parents": '包括隐藏的父级',
    "Reached Top of Hierarchy": '到达层级顶部',
    "Reached ABSOLUTE Top of Hierarchy": '已达到层级结构的绝对顶端',
    "Selecting Up ": '向上选择',
    "+ Unhiding ": '取消隐藏',
    "+ Recursive ": '递归',
    "+ Inclusive": '包容',
    "Reached Bottom of Hierarchy": '到达层级底部',
    "with {} Hidden Children": '包括隐藏的子级',
    "Reached ABSOLUTE Bottom of Hierarchy": '已达到层级结构的绝对底部',
    "Selecting Down ": '向下选择',
    "Nothing to remove.": '没有可删除的内容。',
    "Filebrowser": '文件浏览器',
    "Overlay Visibility (per-shading type)": '叠加显示性(每种阴影类型)',
    "Solid Shading": '纯色着色',
    "Material Shading": '材质着色',
    "Rendered Shading": '渲染着色',
    "Wire Shading": '线框着色',
    "Switch Background too": '同时切换背景',
    "Force Single Color Shading for Matcap 2": '为Matcap 2强制单色着色',
    "Disable Overlays for Matcap 2": '禁用Matcap 2的叠加层',
    "Force Trackball Navigation when using Custom Views": '在使用自定义视图时强制轨迹球导航',
    "Set Transform Preset when using Custom Views": '在使用自定义视图时设置变换预设',
    "Show Orbit around Active": '显示围绕活动物体的轨道',
    "Show Turntable/Trackball Orbit Method Selection": '显示转盘/轨迹球轨道选择方法',
    "Thread": '螺纹',
    "\nSHIFT: Extend Selection": '\nSHIFT：扩展选择',
    "\n   or": '\n   或者',
    "\nCTRL: Contract Selection": '\nCTRL：收缩选择',
    "\nCTRL: Expand Selection": '\nCTRL：扩展选择',
    "{} Select": '{} 选择',
    "Switch to {} Mode": '切换到{}模式',
    "Control shading, overlays, eevee and some object properties": '控制着色、覆盖、Eevee 和部分对象属性',
    'Select Center Objects':'选择中心对象',
    'Select Wire Objects':'选择线框对象',
    'Apply Transformations':'应用变换',
    'Align Relative':'相对对齐',
    'Material Picker':'材质选择器',
    'No Materials added yet!':'尚未添加材质！',
    'Check Kourin_tooltools prefs.':'检查 Kourin_tooltools 首选项。',
    '(X) Un-Group':'（X）取消分组',
    '(Q) Setup Group Gizmos':'（Q）设置群组图标',
    'Quad Sphere':'四面体球',
    'Cursor Spin':'光标旋转',
    'Punch It':'推进',
    'Quick Render':'快速渲染',
    'Final Render':'最终渲染',
    'Seed Count':'种子数量',
    'Seed Render':'种子渲染',
    'Final Seed Render':'最终种子渲染',
    'Edit':'编辑',
    'Apply Transformations while keeping the bevel width as well as the child transformations unchanged.':'将变换应用到对象，同时保持斜角宽度以及子对象的变换不变。',
    "Rotate Group '{}' around its {} Axis":"将 '{}' 组绕其 {} 轴旋转",
    'ℹℹ Illegal Selection ℹℹ':'ℹℹ  非法选择  ℹℹ',
    "You can't create a group from a selection of Objects that are all already parented to something (other other than group empties)":"你不能从已经都有父级关联的对象（除了群组空对象之外）的选择中创建群组。",
    '{} Goup: {}':'{} 组: {}',
    'Sub':'子',
    'Root':'根',
    "Added {} objects to group '{}'":"已将 {} 个对象添加到群组'{}'",
    'Removed {} objects from their group':"从它们的群组中移除了 {} 个对象",
    'Kourin_tool: Toggle Outliner Children':'Kourin_tool:切换大纲子项',
    'Kourin_tool: Toggle Outliner Group Mode':'Kourin_tool:切换大纲组模式',
    'Kourin_tool: Collapse Outliner':'Kourin_tool: 折叠大纲视图',
    'Kourin_tool: Expand Outliner':'Kourin_tool: 展开大纲视图',
    'Pose: {}{}':'姿势: {}{}',
    ' (remove)':' (移除)',
    'Preview Alpha: {}':'预览透明: {}',
    'Kourin_tool: Transform Group':'Kourin_tool: 变换图层组',
    'Pose: ':'姿势: ',
    'Alpha: ':'透明度: ',
    'Kourin_tool: Setup Group Gizmos':'Kourin_tool: 设置组小部件',
    'show_group_{}_rotation':'显示组 {} 的旋转',
    ' Global: {}':' 全局: {}',
    'Kourin_tool: Set Group Pose':'Kourin_tool: 设置组姿态',
    'Kourin_tool: Update Group Pose':'Kourin_tool: 更新组姿态',
    'Update Up':'更新朝上',
    'Update Poses Up the Hierarchy too':'同时更新层次结构上方的姿态',
    'Update Unlinked':'更新未链接的',
    'Update Poses, that have been unlinked too':'同时更新那些已经被取消链接的姿态',
    'Edit Mode':'编辑模式',
    'Horizontal':'水平',
    'Vertical':'垂直',
    'Shortest Path':'最短路径',
    'in Center':'居中',
    'Topo':'拓扑',
    'Select more than 1 vertex.':'选择了多个顶点。',
    'Select the last vertex without Box or Circle Select.':'不使用框选或圆形选择,选择最后一个顶点。',
    'Try to position the view and mouse in a way, that clearly indicates the direction you want to slide towards':'尝试调整视角和鼠标位置,以清楚地指示您想要沿哪个方向滑动。',
    'Use Focus':'使用聚焦',
    'Surface Slide':'表面滑动',
    'Align to':'对齐到',
    'Degenerate':'简化',
    'Merge to closeby Vert':'合并到临近的顶点',
    'Focus on new Object':'聚焦新物体',
    'Kourin_tool: Smart Vert':'Kourin_tool: 智能顶点',
    'Kourin_tool: Smart Edge':'Kourin_tool: 智能边',
    'Kourin_tool: Smart Face':'Kourin_tool: 智能面',
    'Kourin_tool: Clean Up':'Kourin_tool: 清理',
    'Kourin_tool: Clipping Toggle':'Kourin_tool: 裁切变换',
    'Kourin_tool: Focus':'Kourin_tool: 聚焦',
    "Kourin_tool: Mirror":'Kourin_tool: 镜像',
    'Kourin_tool: Call Kourin_tooltools Pie':'Kourin_tool: 呼出菜单',
    "Kourin_tool: Open in System's filebrowser":'Kourin_tool: 在系统文件浏览器中打开',
    'Kourin_tool: Toggle Filebrowser':'Kourin_tool: 切换文件浏览器',
    'Kourin_tool: Cycle Thumbnail Size':'Kourin_tool: 循环缩略图大小',
    'Kourin_tool: Group':'Kourin_tool: 打组',
    'Kourin_tool: Select Group':'Kourin_tool: 选择组',
    'Kourin_tool: Transform Edge Constrained':'Kourin_tool: 受约束的边缘变换',
    'Kourin_tool: Duplicate Nodes':'Kourin_tool: 复制节点',
    'Modes':'模式',
    'UV Align':'uv对齐',
    'Inception':'初始',
    'LegacyPose':'初始姿态',
    'Kourin_tool: Align':'Kourin_tool: 对齐',
    'Kourin_tool: Align Relative':'Kourin_tool: 相对对齐',
    'Kourin_tool: Apply Transformations':'Kourin_tool: 应用变换',
    'Kourin_tool: Create Assembly Asset':'Kourin_tool: 创建装配资产',
    'Kourin_tool: Assetbrowser Bookmark':'Kourin_tool: 资产浏览器书签',
    'Kourin_tool: Customize':'Kourin_tool: 自定义',
    'Customize various Blender preferences, settings and keymaps.':'自定义各种Blender首选项、设置和快捷键。',
    'Kourin_tool: Restore Keymaps':'Kourin_tool: 恢复快捷键',
    'Kourin_tool: Punch It':'Kourin_tool: 打孔',
    'Manifold Extruding that works':'有效的多曲面挤出',
    'Kourin_tool: Cursor Spin':'Kourin_tool: 光标旋转',
    'Kourin_tool: Un-Group':'Kourin_tool: 取消分组',
    'Kourin_tool: Groupify':'Kourin_tool: 分组',
    'Kourin_tool: Material Picker':'Kourin_tool: 材质取色器',
    'Pick a Material from the 3D View\nALT: Assign it to the Selection too':'从3D视图中选取材质\nALT: 同时将其分配给选择',
    'Kourin_tool: Mesh Cut':'Kourin_tool: 网格切割',
    'Kourin_tool: Quadsphere':'Kourin_tool: 四边形球体',
    'Creates a Quadsphere':'创建一个四边形球体',
    'Kourin_tool: Toggle 3D View Region':'Kourin_tool: 切换3D视图区域',
    'Kourin_tool: Toggle Asset Browser Region':'Kourin_tool: 切换资产浏览器区域',
    'Toggle Asset Browser Region based on Mouse Position':'根据鼠标位置切换资产浏览器区域',
    'Kourin_tool: Toggle Toolbar or Sidebar (Any Region)':'Kourin_tool: 切换工具栏或侧边栏(任何区域)',
    'Toggle Toolbar or Sidebar (Any Region)':'切换工具栏或侧边栏(任何区域)',
    'Kourin_tool: Area Dumper':'Kourin_tool: 区域dump器',
    'Kourin_tool: Render':'Kourin_tool: 渲染',
    'Duplicate Nodes normaly, except for Cryptomatte V2 nodes, in that case keep the inputs and clear out the matte ids':'正常复制节点,但对于Cryptomatte V2节点,保留输入并清除遮罩ID。',
    'Kourin_tool: Smart Drive':'Kourin_tool: 智能驱动',
    'Kourin_tool: Switch Driver Values':'Kourin_tool: 切换驱动器值',
    'Kourin_tool: set_driver_value':'Kourin_tool: 设置驱动器值',
    'Kourin_tool: Toggle Smooth':'Kourin_tool: 切换平滑',
    'Toggle Smothing for Korean Bevel and SubD Objects':'切换韩式斜角和细分网格物体的平滑设置。',
    'Kourin_tool: Surface Slide':'Kourin_tool: 表面滑动',
    'Start Surface Sliding: modifify the topology while keeping the inital form intact':'开始表面滑动:在保持初始形状完整的情况下修改拓扑结构。',
    'Kourin_tool: Finish Surface Slide':'Kourin_tool: 完成表面滑动',
    'Stop Surface Sliding':'停止表面滑动',
    'Kourin_tool: Add Thread':'Kourin_tool: 添加螺纹',
    'Kourin_tool: Prepare Unity Export':'Kourin_tool: 准备Unity导出',
    'Kourin_tool: Restore Unity Export':'Kourin_tool: 恢复Unity导出',
    'Restore Pre-Export Object Transformations, Meshes and Modifiers':'恢复导出前的物体变换、网格和修改器设置。',
    'Kourin_tool: Draw Group Rest Pose':'Kourin_tool: 绘制组静止姿态',
    'Reverse the Motion':'反转动作',
    'Time (s)':'时间(秒)',
    'Kourin_tool: Align (Edit Mesh)':'Kourin_tool: 对齐(编辑网格)',
    'Kourin_tool: Align Object to Edge':'Kourin_tool: 将物体对齐到边缘',
    'Kourin_tool: Center (Edit Mesh)':'Kourin_tool: 居中(编辑网格)',
    'Align one or more objects to edge in active object\nALT: Snap objects to edge by proximity\nCTRL: Snap objects to edge by midpoint':'将一个或多个物体对齐到活动物体的边缘\nALT: 根据相邻性将物体卡到边缘\nCTRL: 根据中点将物体卡到边缘',
    'Kourin_tool: Align Object to Vert':'Kourin_tool: 将物体对齐到顶点',
    'Align one or more objects to vertice in active object':'将一个或多个物体对齐到活动物体的顶点',
    'Kourin_tool: Straighten':'Kourin_tool: 拉直',
    'Kourin_tool: Create Collection':'Kourin_tool: 创建集合',
    'Kourin_tool: Remove from Collection':'Kourin_tool: 从集合中移除',
    'Kourin_tool: Purge Collections':'Kourin_tool: 清除集合',
    'Kourin_tool: (De)Select Collection':'Kourin_tool: (取消)选择集合',
    'Kourin_tool: Cursor to Origin':'Kourin_tool: 光标移动到原点',
    'Kourin_tool: Cursor to Selected':'Kourin_tool: 光标移动到所选位置',
    'Kourin_tool: Selected To Cursor':'Kourin_tool: 所选物体移动到光标位置',
    'Kourin_tool: Draw Label':'Kourin_tool: 绘制标签',
    'Text to draw the HUD':'绘制HUD的文本',
    'Text Size':'文本大小',
    'Screen Coordinates':'屏幕坐标',
    'Move Up or Down':'上下移动',
    'Kourin_tool: ShrinkWrap Grease Pencil':'Kourin_tool: 收缩铺路铅笔',
    'Shrinkwrap current Grease Pencil Layer to closest mesh surface based on Surface Offset value':'根据表面偏移值,将当前铅笔图层收缩到最近的网格表面',
    'Kourin_tool: Get Kourin_tooltools Support':'Kourin_tool: 获取Kourin_tool工具支持',
    'Generate Log Files and Instructions for a Support Request.':'生成日志文件并提供支持请求的说明。',
    'Kourin_tool: Image Mode':'Kourin_tool: 图像模式',
    'Kourin_tool: UV Mode':'Kourin_tool: UV模式',
    'Kourin_tool: Open Library Blend':'Kourin_tool: 打开库Blend文件',
    'Open new Blender instance, loading the library sourced in the selected object or collection instance.':'打开一个新的Blender实例,加载在所选物体或集合实例中引用的库文件。',
    'Kourin_tool: Origin to Active':'Kourin_tool: 原点移动到活动物体',
    'Kourin_tool: Origin to Cursor':'Kourin_tool: 原点移动到光标位置',
    'Kourin_tool: Origin to Bottom Bounds':'Kourin_tool: 原点移动到物体底部边界',
    'Evaluated Object Bounds':'评估物体边界',
    'Kourin_tool: Save As':'Kourin_tool: 另存为',
    'Save as Copy':'另存为副本',
    'Save as Asset':'另存为资产',
    'Purge Orphans\nALT: Purge Orphans Recursively':'清理孤立元素\nALT: 递归清理孤立元素',
    'Shading Type':'着色类型',
    'Adjust Global Bevel Radius':'调整全局斜角半径',
    'Decrease Radius':'减小半径',
    'Kourin_tool: Set Snapping Preset':'Kourin_tool: 设置吸附预设',
    'Set Snapping Preset':'设置吸附预设',
    'Snap Element':'吸附元素',
    'Snap Target':'吸附目标',
    'Align Rotation':'对齐旋转',
    'Kourin_tool: Set Tool by Name':'Kourin_tool: 按名称设置工具',
    'Tool name/ID':'工具名称/ID',
    'Kourin_tool: Set BoxCutter Preset':'Kourin_tool: 设置BoxCutter预设',
    'Quickly enable/switch BC tool in/to various modes':'快速启用/切换BoxCutter工具到各种模式',
    'Kourin_tool: Set Transform Preset':'Kourin_tool: 设置变换预设',
    'Set Transform Pivot and Orientation at the same time.':'同时设置变换枢轴和方向。',
    'Transform Pivot':'变换枢轴',
    'Transform Orientation':'变换方向',
    'Kourin_tool: Remove Update':'Kourin_tool: 移除更新',
    "I changed my mind, I don't want to install this Update":"我改变主意了,我不想安装这个更新。",
    'Kourin_tool: Use Update':'Kourin_tool: 使用更新',
    'Kourin_tool: Re-Scan Updates':'Kourin_tool: 重新扫描更新',
    'Re-Scan Updates':'重新扫描更新',
    'Kourin_tool: Align (UV)':'Kourin_tool: 对齐(UV)',
    'Kourin_tool: Get Icon Name Help':'Kourin_tool: 获取图标名称帮助',
    'Top.':'上',
    'Bottom.':'下',
    'Assign':'分配',
    'Assign Material from Asset Browsr to Object under Mouse':'从资产浏览器中将材质分配给鼠标下的物体',
    'Pick Material and Assign it to Selected Objects':'选择材质并将其分配给选定的对象',
    'Pick Material and Finish':'选择材质并完成',
    'Assign Material: {}':'分配材质: {}',
    'Assign Material from Asset Browser: {}':'从资产浏览器分配材质: {}',
    'Assign from Asset Browser ':'从资产浏览器分配',
    'Pick':'拾取',
    '.blend file does not exist: {}':'.blend文件不存在: {}',
    'No material selected in asset browser!':'在资产浏览器中未选择任何材质!',
    'LOCAL or unsupported library chosen!':'选择了本地或不支持的库!',
    'Material ':'材质 ',
    'There is no asset browser in this workspace':'这个工作空间中没有资产浏览器',
    'Quick Favorites':'快速收藏夹',
    'Tool Bar':'工具栏',
    "Pick Materials from the Material Workspace's 3D View":'从材质工作空间的3D视图中选取材质',
    'Collection':'集合',
    'Based on the M4 tool, add more features to make Blender more user-friendly':'基于M4工具,添加更多功能来使Blender变得更加好用',
    'Object Mode Header Spacing':'物体模式标题间距',
    'Edit Mode Header Spacing':'编辑模式标题间距',
    'Show Material Picker':'显示材质选择器',
    'Show Material Picker in Views set to Material Shading':'在设置为材质着色的视图中显示材质选择器',
    'Show Material Picker in Views set to Rendered Shading':'在设置为渲染着色的视图中显示材质选择器',
    'Workspaces the Material Picker should appear on':'材质选择器应该出现在的工作空间',
    'Include Children':'包含子项',
    'Individual':'各自的原点',
    'Absolute Grid':'绝对网格',
    'Surface':'表面',
    'Snap to Vertices':'吸附到顶点',
    'Snap to Edges':'吸附到边',
    'Snap to Faces and Align the Rotation':'吸附到面并对齐旋转',
    'Snap to Absolute Grid Points':'吸附到绝对网格点',
    'Snap to Volumes':'吸附到体积',
    'Show Absolute Grid Snapping':'显示绝对网格吸附',
    'Show Volume Snapping':'显示体积吸附',
    'Transform Pie':'变换菜单',
    'Snapping Pie':'吸附菜单',
    'Movement of an object up, down, left and right based on perspective control and selection':'基于视角控制选择物体上下左右移动',
    'Control Move':'上下左右',
    'Control Move Offset':'移动精度',
    'Upward movement':'向上移动',
    'Downward movement':'向下移动',
    'Left movement':'向左移动',
    'Right movement':'向右移动',
    'Move towards the view':'靠近视角',
    'Move away from the view':'远离视角',
    'Move Control':'移动控制',
    'Kourin_tool:HDR Rotation':'Kourin_tool:HDR旋转',
    'Hdr Rotation':'HDR旋转',
    'Rotation HDR by Shift+Right Drag in 3D View':'在3D视图中,通过按住Shift+右拖拽来旋转HDR',
    'This will restore all Kourin_tooltools Keymappings, that have been removed':'这将恢复所有已删除的 Kourin_tooltools 键位映射',
    'This will undo all Kourin_tooltools Keymap changes you have done':'这将撤销您所做的所有 Kourin_tooltools 键位映射更改。',
    'Only RMB is supported for now! You could add a modifier key like SHIFT or ALT though.':'目前只支持右键鼠标（RMB）！不过您可以添加像 SHIFT 或 ALT 这样的修饰键',
    'in 3D View':'3D视图',
    'in Image Editor':'图片浏览器',
    'Save Startup File':'保存版本化启动文件',
    'in Edit Mode':'编辑模式',
    'in UV Editor':'UV编辑器',
    'Adjust Thumbnail Size':'调整缩略图大小',
    'Kourin_tool: Adjust Thumbnail Size':'Kourin_tool: 调整缩略图大小',
    'Bookmark ^':'书签 ^',
    'Bookmark 1':'书签 1',
    'Bookmark 2':'书签 2',
    'Bookmark 3':'书签 3',
    'Bookmark 4':'书签 4',
    'Bookmark 5':'书签 5',
    'Bookmark 6':'书签 6',
    'Bookmark 7':'书签 7',
    'Bookmark 8':'书签 8',
    'Bookmark 9':'书签 9',
    'Bookmark 10':'书签 10',
    'Assetbrowser':'资产浏览器',
    '{} Screen Cast':'{} 屏幕快捷键',
    'Enable':'开启',
    'Disable':'关闭',
    'Asset Info':'资产信息',
    'Asset Name':'资产名',
    'Create Assembly Asset from the selected Objects':'从选定对象创建组件资产',
    'Asset Empty':'资产空物体',
    'Avg. Floor':'平均 地面',
    'Averaged Location of all Asset Root Objects projected on the floor':'所有资产根对象在地面上的平均位置投影',
    'Averaged Location of all Asset Root Objects':'所有资产根对象的平均位置',
    'World Origin':'世界原点',
    'Scene Collection':'场景集合',
    'Object Collections':'物体集合',
    'Add Asset empty to Scene Collection':'将空资产添加到场景集合中',
    "Add Asset Empty to Asset Object's Colletion(s)":'将空资产添加到资产对象的集合中',
    'Render Thumbnail':'渲染缩略图',
    'Unlink Assembly Asset':'解除链接组件资产',
    'Empty Location':'空物体位置',
    'Move instead of Copy':'移动而不是复制',
    'Move Objects into Asset Collection, instead of copying\nThis will unlink them from any existing collections':'将对象移动到资产集合中，而不是复制。这将使它们与任何现有集合解除链接。',
    "Location of Asset's Empty":'资产空对象的位置',
    'Remove the Asset Empty from the current Scene':'从当前场景中移除资产空对象',
    'Reload Libraries':'重新加载库',
    'Create Assembly Asset':'创建组件资产',
    'Clean out entire .blend file':'清理整个 .blend 文件',
    ' (except selected objects)':' (除选定对象外)',
    '\nALT: Remove non-default Brushes too':'\n按住ALT同时移除非默认笔刷',
    'This will remove everything in the current .blend file':'这将删除当前 .blend 文件中的所有内容',
    ', including custom Brushes':', 包括自定义笔刷',
    ', but except the selected objects':'除了选中的物体',
    ', except the selected objects':'除了选中的物体',
    'Colorize Scene Materials':'为场景材质上色',
    'Shading and Overlays':'着色和叠加层',
    'wireframe_xray':'线框 透视',
    'wireframe':'线框',
    'Wireframe (all + selection)':'线框 (全部 + 选中)',
    'Wireframe (all)':'线框 (全部)',
    'Wireframe (selection)':'线框 (选中)',
    'Wireframe (Active)':'线框 (激活)',
    'Opacity':'透明',
    'Assign from Assetbrowse/r':'从资产浏览器分配',
    'Assign to Object Under Mouse':'分配给鼠标下的对象',
    'Finish':'完成',
    'Clear Materials + Finish':'清除材质 + 完成',
    'Viewport':'视口',
    'Cancel':'取消',
    'Assign to Selection: {}':'指定到选中',
    'Pick and/or assign Material from the 3D View, or batch assign from the Assetbrowser':'从 3D 视图中选择和/或分配材质，或从资产浏览器批量分配',
    ' from Asset Browser ':'从资产浏览器',
    'to: ':'到:',
    'Material: ':'材质:',
    'Face Selection':'选中面',
    ' from: ':'从:',
    'There is no active asset browser in this workspace, move the mouse over one to make it active':'此工作区中没有活动的资产浏览器，将鼠标移动到一个上以使其激活',
    'There is no selected Material Asset in the active asset browser':'在活动的资产浏览器中没有选定的材质资产',

    'Collection Name':'集合名',
    'Group':'打组',
    'Disassemble':'拆解',
    'Remove Assembly':'移除组合',
    'Make Local':'本地化',
    'Open {}':'打开 {}',
    'Remove Asset':'移除资产',
    'Update Thumbnail':'更新缩略图',
    'Assembly':'组合',
    'is {}Local Asset Instance':'是 {}本地资产实例',
    'recursive ':'递归的',
    'Update the Asset Thumbnail via a Viewport Render of the Active Object':'通过活动对象的视口渲染更新资产缩略图',
    'Remove entire Local Asset':'移除整个本地资产',
    'This will remove the entire asset from the .blend file!':'这将从 .blend 文件中移除整个资产',
    'It will no longer be available in the asset browser after this operation.':'在此操作后，它将不再在资产浏览器中可用',
    'Remove entire Local Assembly Asset from the file. Careful, this removes it from from the Asset Browser too':'从文件中移除整个本地组装资产。请注意，这也会从资产浏览器中移除',
    'Remove Assembly Object.\nIf its instance collection has no other users, remove it and the contained objects too':'移除组合对象。\n如果它的实例集合没有其他使用者，则同时移除它和其中的对象',
    'Make Assembly Objects (Instance Collection) accessible':'“使组装对象（实例集合）可访问。”',
    'Align Custom View to Active Object\nALT: Align View to Active {}':'将自定义视图对齐到活动对象\nALT：将视图对齐到活动 {}',
    'Align Custom View to Cursor\nALT: Align View to Active {}':'将自定义视图对齐到光标\nALT：将视图对齐到活动 {}',
    'Align View to World\nALT: Align View to Active to Active {}':'将视图对齐到世界\nALT：将视图对齐到活动 {}”',
    'Prepare and Export {} objects':'准备并导出 {} 对象',
    'Prepare {} objects for Export to Unity':'准备 {} 对象以导出到 Unity',
    'selected':'选中',
    'visible':'可见',
    'Cycle Display Type: {}':'循环显示类型：{}',
    'Switch to Next Camera':'切换下一个相机',
    'Switch to Previous Camera':'切换上一个相机',
    "Switch to Workplace '{}' and sync Viewport\nALT: Also sync Shading and Overlays":"切换到工作区 '{}' 并同步视口\nALT：同时同步着色和叠加效果",
    'There is a conflicting keymap, preventing the Shading Pie from coming up in Sculpt mode. I suggest you remap it, maybe by adding a mod key?':'这里有一个冲突的键位映射，阻止了在雕刻模式下显示着色饼图。我建议你重新映射它，也许可以添加一个修改键',
    'There is a conflicting keymap, preventing the Views Pie from coming up in Sculpt mode. I suggest you remap it, maybe by adding a mod key?':'有一个冲突的键位映射，阻止了在雕刻模式下显示视图饼图。我建议你重新映射它，也许可以添加一个修改键',
    'Match Resolution and Camera Lens to Viewport':'将分辨率和摄像机镜头匹配到视口',
    'Smart Cam':'智能相机',
    'Camera Creation':'相机创建',
    "Leave Auto Smooth Modifier open, and don't collapse it":'保持自动平滑修饰符打开，不要折叠它',
    'Modal Thumbnail Size Adjustment':'模态缩略图大小调整',
    'Right Mouse Button Keymap':'右键鼠标键位映射',
    'Basename':'基本名称',
    'Use RMB to Assign Material to selection in Material and Rendered shading modes':'在材质和渲染着色模式下，使用右键鼠标按钮将材质分配给选定对象',
    'Transform Orientations and Pivots':'变换方向和旋转中心',
    'Show Annotate':'显示注释',
    'Show Surface Draw':'显示表面绘制',
    'Show SurfaceDraw':'显示表面绘制',
    'Automatically add a Prefix and/or Suffix to any user-set Group Name':'自动向用户设置的组名添加前缀和/或后缀',
    'Group Basename':'组基础名称',
    'Group Empty Draw Size':'组空对象绘制大小',
    'Default Group Size':'默认大小',
    "Make Sub Group's Emtpies smaller than their Parents":'使子组的空对象比其父对象小',
    "Factor by which to decrease each Group Empty's Size":'用于减小每个组空对象大小的因子',
    'Prefix to add to Group Names':'添加到组名前的前缀',
    'Suffix to add to Group Names':'添加到组名前的后缀',
    'Maximum number of Operators displayed when Screen Casting':'屏幕捕捉时显示的最大操作员数量',
    'This is useful for Unity, but bad for Unreal Engine':'这对Unity很有用，但对Unreal Engine不利',
    'Export Root Folders':'导出根文件夹',
    'Edit Mode Spacing':'编辑模式间距',
    'Object Mode Spacing':'物体模式模式间距',
    'Bookmark: {}':'书签',
    '\n Library: Current File':'\n 库：当前文件',
    '\n Library: ALL ({})':'\n 库：全部 ({})',
    '\n Library: {}':'\n 库: {}',
    '\n Catalog: {}':'\n 目录：{}',
    '\n None':'\n 无',
    "\n\nClick: Jump to this Bookmark's Library and Catalog":'\n\n点击：跳转到此书签的库和目录',
    '\nSHIFT: Save the current Library and Catalog on this Bookmark':'\nSHIFT：在此书签上保存当前的库和目录',
    '\nCTRL: Remove the stored Bookmark':'\nCTRL：移除已存的书签',
    'Location':'位置',
    'Ungroupable':'不可分组',
    'Object is parented':'对象被关联到父级',
    'Align in between':'居中对齐',
    'Draw in between':'在中间绘制',
    'Flip':'翻转',
    'Align Location':'对齐位置',
    'Parent to Bone':'父级绑定到骨骼',
    'Align Scale':'对齐缩放',
    'Align Z to Y':'将 Z 轴对齐到 Y 轴',
    '滚动量(以度为单位)':'Roll Amount in Degrees',
    'Rotation':'旋转',
    'Scale':'缩放',
    'Show Annotation Tools':'显示注释工具',
    'Show GreasePencil Surface Draw Tool':'显示油脂铅笔表面绘图工具',
    'Confirm':'确认',
    'Select Single':'选择单个',
    'Select Multiple':'选择多个',
    'Instance: {}':'实例: {}',
    'Instance':'实例',
    'Duplicate':'复制',
    'Catalog':'目录',
    'Could not create Asset Thumbnail from current Selection of Objects':'无法从当前选择的对象创建资产缩略图',
    "The chosen asset name can't be nothing":'所选择的资产名称不能为空',
    'Illegal Name':'非法名称',
    'Legacy Asset Objects have been disassembled, but not removed automatically!':'遗留资产对象已被拆解，但未自动移除！',
    "This is because Kourin_tooltools can't be sure they aren't the original objects":'这是因为 Kourin_tooltools 无法确定它们不是原始对象',
    'Please remove manually, if desired':'如果需要，请手动移除',
    'Kourin_tool: Make IDs Local':'Kourin_tool：使 ID 本地化',
    'Make object data, including instance collections local':'使对象数据，包括实例集合，本地化。',
    'Make linked objects local':'使链接对象本地化',
    '\nSHIFT: make object data, including instance collections local':'\nSHIFT：使对象数据，包括实例集合，本地化',
    '\n\nSelection contains {} linked data blocks':'\n\n选择包含 {} 个链接数据块。',
    'Remove Doubles':'删除重复',
    'Dissolve Degenerate':'溶解退化',
    'Merge Distance':'合并距离',
    'Flip Normals':'反转法线',
    'Delete Loose':'删除松散',
    'Delete Loose Verts':'删除松散顶点',
    'Delete Loose Edges':'删除松散边',
    'Delete Loose Faces':'删除松散面',
    'Dissolve Redundant':'消除冗余',
    'Dissolve Redundant Verts':'消除冗余顶点',
    'Dissolve Redundant Edges':'消除冗余边',
    'Dissolve Redundant Angle':'消除冗余角度',
    'Non-Planar Face Threshold':'非平面面片阈值',
    'Threshold':'阈值',
    'Removed:{}{}{}':'已移除：{}{}{}',
    ' Edges: ':' 边: ',
    ' Verts: ':' 顶点: ',
    ' Faces: ':' 面: ',
    'Non-Manifold Edges found!':'发现非流形边！',
    'Minimum':'最小值',
    'Medium':'中间值',
    'Maximum':'最大值',
    'Current State':'当前状态',
    'state':'状态',
    'Current':'当前',
    'Minimum: {} ':'最小值：{}',
    'Medium: {}':'中间值: {}',
    ' Maximum: {}':' 最大值: {}',
    'Clip Start':'裁切起点',
    'Zero Scaling':'零缩放',
    'Clear Axis':'清空轴',
    'Transform Mode':'变换模式',
    'Transform Axis':'变换轴',
    'Align Ends to Face Edge':'将末端对齐到面边缘',
    'Draw Align Ends Option':'绘制对齐末端选项',
    'Face Align':'面对齐',
    'Set Amount':'设置总数',
    'Finalize':'最终',
    'Extrusion Mode:':'挤出模式：',
    'Averaged':'平均',
    'Reset Amount':'重置数量',
    'Sorcery':'玄学修复',
    'Push and Pull':'推拉',
    'Pushed':'推',
    'Pull':'推',
    'Pulled':'拉',
    'Push':'拉',
    'Push Side Faces out':'将侧面推出（或向外推）',
    'Pull Front Face back':'将前面拉回（或向后拉）',
    'Push/Pull x 100':'推/拉 x 100',
    '"Pushing" means widening the extrusion, moving the blue faces outwards':'推动意味着扩展挤压物，将蓝色的面向外移动',
    '"Pulling" means moving the green faces back':'拉动意味着将绿色的面向后移动',
    "Magically fix issues (slower)\nDisabled you'll often need bigger Push and Pull values (faster)":'神奇地修复问题（较慢）\n禁用后，您通常需要更大的推拉值（更快）',
    'Use Self Intersection':'使用自相交',
    'Finalizing':'完成',
    'magically':'玄学修复',
    'Pushed: {}':'推: {}',
    'Pulled: {}':'拉: {}',
    'valid':'有效',
    'invalid':'无效',
    'none':'无',
    'You need to select at least one edge':'你需要至少选择一条边',
    'Illegal Selection!':'非法选择！',
    'Select at least one face, duh!':'至少选择一个面',
    'Pay attention, numbnuts!':'注意',
    "Open the current location in the System's own filebrowser\nALT: Open .blend file":'在系统自带的文件浏览器中打开当前位置\nALT: 打开 .blend 文件',
    'The blend file containing this asset is already open.':'包含此资源的 .blend 文件已打开。',
    'Toggle/Cycle SORT, DISPLAY_TYPE, HIDDEN':'切换/循环 排序（SORT）、显示类型（DISPLAY_TYPE）、隐藏（HIDDEN）',
    'very big':'非常大',
    'very smol':'非常小',
    'Method':'方式',
    'Levels':'层级',
    'Switch between single-level Blender native Local View and multi-level Kourin_tool Focus':'在单级的 Blender 本地视图和多级的 Kourin_tool Focus 之间切换',
    'Inverted Focus':'反向聚焦',
    '{} Group: {}':'{} 组: {}',
    '{}/{} Objects could not be grouped':'{}/{} 个对象无法分组',
    'Un-Group all Selected Groups':'取消选定的所有组',
    'Un-Group entire Hierarchy down':'取消整个层级向下分组',
    'Add Color':'添加颜色',
    'Add Mirror':'添加镜像',
    "Adjust Size: {}":'调整大小: {}',
    'Toggle Axis Gizmo based on View: {}':'根据视图切换轴控件: {}',
    'X Axis Gizmo: {}':'X 轴控件: {}',
    'Y Axis Gizmo: {}':'Y 轴控件: {}',
    'Z Axis Gizmo: {}':'Z 轴控件: {}',
    'Lock Axes without Gizmos: {}':'锁定轴而不显示控件: {}',
    'Show Gizmo{}: {}':'显示控件{}: {}',
    'Lock Rotational Axes without Gizmos':'锁定旋转轴而不显示控件',
    'No Material selected in asset browser!':'资产浏览器中未选择材质！',
    "Flatten Target":'展平目标',
    'Mirror':'镜像',
    'Pick Axis':'选择轴向',
    'Cursor: {}':'游标: {}',
    'Use Existing: {}':'使用现有: {}',
    'Remove All + Finish':'全部移除并完成',
    'Remove Mirror: {}':'移除镜像: {}',
    'Toggle Mirror Object: {}':'切换镜像对象: {}',
    'Cycle Mirror Object':'循环镜像对象',
    'Flick':'快速切换',
    'Bisect':'分割',
    'Cursor Empty':'光标空对象',
    'New Cursor':'新游标',
    'Existing Cursor':'现有光标',
    'Shade Smooth':'Shade Smooth',
    'subdivisions':'细分',
    'Subdivisions':'细分',
    'Toggle 3D View Region based on Mouse Position':'根据鼠标位置切换 3D 视图区域',
    "Library '{}' can not longer be found among registered asset libraries!":"注册的资产库中不再能找到库 '{}'",
    "Screen name '{}' can't be found in previously stored settings!":"屏幕名称 '{}' 在先前保存的设置中找不到！",
    "Can't toggle the Sidebar":'无法切换侧边栏',
    'Insufficient View Space':'视图空间不足',
    "We can't Split this Area in Fullscreen ;(":'无法在此全屏模式下拆分这个区域 ;(',
    "Couldn't apply asset browser settings":'无法应用资产浏览器设置',
    "Then save the blend file, for the change to stick":'然后保存 .blend 文件，以使更改生效',
    "TO FIX IT, DO THIS: Change THIS 3D View into an Asset browser, and back again":'要修复此问题，请执行以下操作：将此 3D 视图切换为资产浏览器，然后再切回',
    "This is normal on a new 3D View!":'这是在新的 3D 视图中的正常现象！',
    "WARNING: Assetbrowser couldn't be set up yet, due to Blender shenanigans.":'警告：由于 Blender 的原因，资产浏览器目前无法设置。',
    'Quarter Quality':'25%',
    'Half Quality':'50%',
    'Double Quality':'200%',
    'Quadruple Quality':'400%',
    'Render and save to {}':'渲染并保存到 {}',
    'Render {} seeds, combine all, and save to {}':'渲染 {} 个种子，合并所有，并保存到 {}',
    '\nAdditionally force EXR, render Cryptomatte, and set up the Compositor':'此外，强制使用 EXR，渲染 Cryptomatte，并设置合成器',
    '\n\nALT: Half Quality\nSHIFT: Double Quality\nALT + CTRL: Quarter Quality\nSHIFT + CTRL: Quadruple Quality':'\n\nALT: 半质量\nSHIFT: 双质量\nALT + CTRL: 四分之一质量\nSHIFT + CTRL: 四倍质量',
    'Switch Start and End {} Values':'切换开始和结束 {} 值',
    'Set {} {} Value':'设置 {} {} 值',
    'Toggle Sharp':'切换锐化',
    'Sharp Mode':'锐化模式',
    'Weight':'权重',
    'Clamp Overlap':'限制重叠',
    'Loop Slide':'循环滑动',
    'Is Unbevel':'是非倒角',
    'Offset Edge Slide':'偏移边缘滑动',
    'Cuts':'切割',
    'Can be Knife Projected':'可以刀具投影',
    'Is Knife Project':'是刀具投影',
    'Cut Through':'穿透切割',
    'Select Mode':'选择模式',
    'Knife Project':'刀具投影',
    'Could not connect vertices':'无法连接顶点',
    'SmartEdge in Bridge mode requires two separate, non-manifold edge loops.':'智能边缘（SmartEdge）在桥接模式下需要两个独立的非流形边环。',
    'Flatten: {}':'展平: {}',
    'Slide Extend Snap to {}':'滑动延伸对齐到 {}',
    'Diverge':'发散',
    'Merge Type':'合并类型',
    'Merge Paths in center':'在中心合并路径',
    'Path Type':'路径类型',
    'Slide Override':'滑动覆盖',
    'Single Vertex Bevelling':'单顶点倒角',
    'Index of Edge accociated with HyperCursor Gizmo, that is to be removed':'与 HyperCursor 控件关联的边缘索引，该边缘将被移除',
    'Can Flatten':'可以展平',
    'Flatten End Face':'展平端面',
    'Toggle Overlays':'切换叠加层',
    'Smooth Mode':'平滑模式',
    'SubD':'细分',
    "You can't Surface Slide on Objects with Shape Keys":'无法在具有形状键的对象上进行表面滑动',
    'Segments':'段数',
    'Threads':'线程',
    'Depth':'深度',
    'Fade':'渐变',
    "Only Prepare, don't export":'仅准备，不导出',
    'Used by DECALmachine to skip Export even if the scene prop is set\nDECALmachine uses its own Export Operator Instead':'用于 DECALmachine 即使场景属性已设置也跳过导出\nDECALmachine 使用其自身的导出操作符',
    'Align to Min or Max, Average, Zero or Cursor':'对齐到最小值或最大值、平均值、零点或光标',
    'Align on the X, Y or Z Axis':'在 X、Y 或 Z 轴上对齐',
    'Align in Local, World or Cursor Space':'在局部、世界或光标空间中对齐',
    'Align Each Island independently':'独立对齐每个岛屿',
    'Hold down ATL, CTRL or neither, not both!':'按下 ATL、CTRL 或两者都不，但不能同时按下两者！',
    'is duplicate name':'是重复名称',
    "Collection '{}' exists already":"集合 '{}' 已经存在",
    'Lighten':'提亮',
    'Least':'最少',
    'Most':'最多',
    'Type':'类型',
    'Parent':'父级',
    'Ignore':'忽略',
    'Multiple Collections':'多个集合',
    'DECALmachine Collections':'DECALmachine 集合层',
    'Reloaded libary {} from {}':'从 {} 重新加载了库 {}',
    "You can't change modes on objects with a Library Override":'无法在具有库覆盖的对象上更改模式',
    'Set Object Origin to Bounding Box Bottom Center':'将对象原点设置为边界框底部中心',
    '\nALT: Determine Bottom Center based on Evaluated Mesh, taking Modifiers into account':'\nALT：根据评估后的网格确定底部中心，考虑修改器的影响',
    'Saved "{}"':'已保存 “{}”',
    'Save {}':'保存 {}',
    'Save {} incrementally to {}\nALT: Save to {}':'将 {} 逐步保存到 {}\nALT：保存到 {}',
    "File '{}' exists already!\nBlend has NOT been saved incrementally!":"文件 '{}' 已经存在！\n.blend 文件未被逐步保存！",
    'Incrementally saved to {}':'逐步保存到 {}',
    'Loaded most recent "{}"':'加载了最近的「{}」',
    'File {} does not exist':'文件 {} 不存在',
    'File not found':'文件未找到',
    'Your are at the beginning of the folder. There are no previous files to load.':'您位于文件夹的开头。没有之前的文件可供加载。',
    'Load Previous .blend File in Current Folder: {}':'在当前文件夹中加载之前的 .blend 文件: {}',
    '\nCTRL: including Backups: {}':'\nCTRL：包括备份文件：{}',
    '\n\nALT: Keep current UI':'\n\nALT：保持当前用户界面',
    "Loaded previous {}file '{}'":"加载了之前的 {} 文件 '{}'",
    'Load Next .blend File in Current Folder: {}':'在当前文件夹中加载下一个 .blend 文件: {}',
    'You have reached the end of the folder. There are no next files to load.':'您已到达文件夹的末尾。没有下一个文件可供加载。',
    "Loaded next {}file '{}'":"加载了下一个 {} 文件 '{}'",
    'BACKUP ':'备份',
    "You have reached the end of blend files in '{}'":"您已到达 '{}' 中的 .blend 文件末尾",
    'There are still some backup files though, which you can load via CTRL':'不过，仍然有一些备份文件，您可以使用 CTRL 加载',
    'End of folder reached':'已到达文件夹末尾',
    'Load UI':'加载 UI',
    "\nSHIFT: Purge Preview":'\nSHIFT：清除预览',
    'Recursive Purge':'递归清除',
    'Purge':'清除',
    'Nothing to purge.':'没有可清除的内容',
    'Remove Custom Brushes':'移除自定义画笔',
    'Has Selected Objects':'有选中对象',
    'Set smooth shading in object and edit mode\nALT: Mark edges sharp if face angle > auto smooth angle':'在对象模式和编辑模式下设置平滑着色\nALT：如果面的角度 > 自动平滑角度，则标记边缘为锐利',
    'Shade Mode':'着色模式',
    'Include Boolean Objects':'包含布尔对象',
    'Set Sharps':'设置锐边',
    'Additive Sharpen':'加性锐化',
    'Avoid removing existing sharps':'避免移除现有的锐边',
    "Avoid Sharpening HyperCursor's Edge Bevels":'避免锐化 HyperCursor 的边缘倒角',
    "Avoid Sharpening Edges used by HyperCursor's Edge Bevels":'避免锐化 HyperCursor 边缘倒角所使用的边缘',
    'Ensure Auto Smooth is enabled, for objects using Boolean Modifiers':'确保使用布尔修改器的对象启用了自动平滑',
    'Boolean Auto Smooth':'布尔自动平滑',
    'Force Setting Auto Smooth Angle, even if Auto Smooth is enabled already':'强制设置自动平滑角度，即使自动平滑已经启用',
    'Clear Sharps, BWeights, Creases and Seams':'清除锐边、权重、折痕和缝合线',
    'Clear BWeights':'清除权重',
    'Clear Creases':'清除折痕',
    'Clear Seams':'清除缝合线',
    'Avoid clearing SubD Creases':'避免清除 SubD 折痕',
    'Avoid Clearing Creases on Objects with SubD mods in crease mode':'避免清除处于折痕模式下的 SubD 对象的折痕',
    'Smooth Flat':'平滑平面',
    'BWeights':'B权重',
    'Apply custom user-made Eevee Preset: {}':'应用自定义用户制作的 Eevee 预设: {}',
    'Raytrace Preset: {}':'光线追踪预设: {}',
    'Element: {}':'元素: {}',
    'Target: {}':'目标: {}',
    'Align Rotation: {}':'对齐旋转: {}',
    'Orientation: {}':'方向: {}',
    'Pivot: {}':'旋转中心: {}',
    'Install Kourin_tooltools {} from {}':'从 {} 安装 Kourin_tooltools {}',
    'You already are in Camera View':'您已经在摄像机视图中了',
    'Created new {}':'创建新 {}',
    'Framed {} Bounds':'框选 {} 范围',
    'Switched to {}':'切换到 {}',
    'Switched to {} {}':'切换到 {} {}',
    'previous':'上一个',
    'next':'下一个',
    'Hold CTRL to snap the DoF Focus empty to a Surface':'按住 CTRL 以将 DoF 焦点空对象对准到表面',
    '{} has been selected':'已选择 {}',
    'Invoke the Translate tool and snap it to a surface using CTRL':'调用移动工具并使用 CTRL 将其对准到表面',
    'General':'通用',
    'About':'关于',
    'Theme':'主题',
    'Extrude along Averaged Face Normals':'沿平均法线挤出',
    'Extrude along any chosen Edge of any Object':'沿任意对象的任意选定边缘挤出',
    'Extrude along Individual Vertex Normals':'沿单独顶点法线挤出',
    'Use Shadows and enable Raytracing':'使用阴影并启用光线追踪',
    'Higher Quality Shadows and Raytracing, enable Bloom and Volumetric Shadows':'高质量阴影和光线追踪，启用发光效果和体积阴影',
    'Even Higher Quality, expect things to be slow, especially when also using Volumetrics':'更高的质量，预期处理速度会较慢，尤其是在使用体积光效时',
    'selected objs':'选中的',
    'Kourin_tool: Vert Merge Path':'Kourin_tool: 合并路径',
    'Kourin_tool: Vert Merge Center':'Kourin_tool: 合并到中心',
    'Kourin_tool: Vert Merge Last':'Kourin_tool: 合并到末选点',
    'Across Objects':'跨物体',
    'Merge vertices across objects':'跨物体合并',
    'Kourin_tool: Vert Connect Path':'Kourin_tool: 连接路径',
    'Ambiguous Direction':'无法判定方向',
    'Apply Rotation':'应用旋转',
    'ccc':'aaa',
}
